### ISSUE TITLE
建议bing搜索默认规则加入匹配项

### ISSUE THREAD

**Issue by zzm-note** [hoothin/SearchJumper#10]
因为很多公司默认ip是香港，所以最好加入一下匹配项：https://(www|cn)\.bing\..*/search。
必应的url写："https://www.bing.com/search?q=%s"，也不会影响大陆地区，因为大陆地区的会自动切换到cn.bing.com。
![image](https://user-images.githubusercontent.com/25860330/173266129-f337c0f0-a320-47f2-8cb5-01614349d0d0.png)

**Comment by hoothin** [comment]
内置的规则就是抛砖引玉的，你可以把这里当作在线仓库，发个issue维护你自己的规则列表
