### ISSUE TITLE
Google on the popup panel doesn't work

### ISSUE THREAD

**Issue by iG8R** [hoothin/SearchJumper#101]
**Describe the bug**
After selecting a text and clicking on the SearchJumper panel's Google gray icon nothing happens.

**To Reproduce**
1. select any text on a web page
2. after SearchJumper's panel appears click on the Google gray icon
3. nothing happens

**Expected behavior**
A new tab should appear with the selected text as the search word.

**Screenshots**

[SearchJumper-not-working-Google-Video_2023-10-31_043438.webm](https://github.com/hoothin/SearchJumper/assets/11407417/f2104fd7-adb4-4465-a19a-e74d3d27191e)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0 64bit
 - SearchJumper: 1.6.30.13

**Comment by hoothin** [comment]
Yes, it's a clone but source of that clone is removed. You can import my full config on github to prevent it.

**Comment by iG8R** [comment]
Thanks a lot!
