### ISSUE TITLE
显示异常：最小化搜索磁贴：仅在输入框上启用

### ISSUE THREAD

**Issue by zhaocai** [hoothin/SearchJumper#105]
**Describe the bug**
启用选项：`最小化搜索磁贴：仅在输入框上启用` 
> 选项设置为`开启`和`关闭`都正常

如下图显示异常，应该是之前版本的问题，出现过我就把这个选项禁用了，没想到这么久还是没修复。

**To Reproduce**
1. 开启选项：`最小化搜索磁贴：仅在输入框上启用`
2. 划词搜索
3. ![20231116_045432](https://github.com/hoothin/SearchJumper/assets/341473/40e351fa-7491-493d-8830-b2ca3acf468a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version latest

**Comment by hoothin** [comment]
感謝反饋，修復了。
應該也不算很久之前的版本的問題，差不多是 iG8R 推動的這一大波更新前後引入的 bug

**Comment by zhaocai** [comment]
感谢感谢，你这效率也太高了😀
