### ISSUE TITLE
维基百科预览弹窗只显示文字，无法显示图片

### ISSUE THREAD

**Issue by snipfork** [hoothin/SearchJumper#108]
**Describe the bug**
维基百科预览弹窗只显示文字，无法显示图片，URL中的html代码有img标签，但无法在预览窗口显示，代码如下：

```html
showTips:https://zh.wikipedia.org/wiki/%s
<div style="max-height: 500px; margin: 5px; overflow: hidden; font-size: large; text-align: left; font-weight: initial; line-height: initial;">
<img style="max-width: 250px; margin: 0 10px;" align="left" src="{.infobox .image>img|src}"/>
{.mw-parser-output>p}
</div>
```

**To Reproduce**
1. 网页中划词
2. Ctrl+右键
3. 鼠标悬浮到【维基百科预览】
4. 弹出预览窗口，但只有文字，无法显示图片

**Expected behavior**
弹出预览窗口中，左边显示图片，被文字环绕

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
可能维基百科是改版了吧？
你可以把`.infobox .image>img|src` 改成 `.infobox img|src` 试试

**Comment by snipfork** [comment]
> 可能维基百科是改版了吧？ 你可以把`.infobox .image>img|src` 改成 `.infobox img|src` 试试

我改成了`figure > a > img|src`，基本可以正常获取图片。`.infobox img|src`很多时候匹配不到图片
