### ISSUE TITLE
how do i disable ui animations

### ISSUE THREAD

**Issue by gmiwoj** [hoothin/SearchJumper#11]
toolbar is great but i absolutely **hate** how it's constantly bouncing around and changing transparency whenever i try to click on things. it's ugly and annoying to use and servers no purpose and i hate it. literally unusable. 

how do i make it sit still and always be visible. i couldn't find any setting for that.

**Comment by hoothin** [comment]
OK, I'll made a option for that soon.
But I'd like to know that how can you trigger ui animations just by click?
Are you checking the option "Select to call"? Why not uncheck it and just call toolbar by long press right mouse?

**Comment by hoothin** [comment]
OK, I'll made a option for that soon.
But I'd like to know that how can you trigger ui animations just by click?
Are you checking the option "Select to call"? Why not uncheck it and just call toolbar by long press right mouse?

**Comment by hoothin** [comment]
You can test the new option now.
Let me know if you have any other suggestion.:-)

**Comment by gmiwoj** [comment]
BETTER! thanks!
