### ISSUE TITLE
正則表達式搜尋得到，但計數是錯的

### ISSUE THREAD

**Issue by EndlessNull** [hoothin/SearchJumper#110]
**Describe the bug**
如題，頁內查找的正則表達式能運作，但顯示的搜尋詞數量是0

**To Reproduce**
1. https://thepiratebay.party/browse/699 （在這能觸發錯誤）
     https://www.1377x.to/top-100-other （在這會正常運作）
2. 搜尋 `/[^.][0-9]{2,}[.0-9  ]*Gi*B/◎GiB` （裡面有無中斷空格）
     改成 `◎/\b[0-9]{2,}.?[0-9]*\s*Gi*B/ ◎/[^.][0-9]+.?[0-9]*\s*Ti*B/` 會是正常的
3. 正則表達式的搜尋顯示 `[0/0]` ，但普通搜尋是 `[1/16]`
![2024-01-23 22:25:49-ScreenshotByFFmpeg](https://github.com/hoothin/SearchJumper/assets/34579128/211f52a4-647a-40d5-9a73-3177e78f8a06)
4. 點擊搜尋詞還是會跳到該去的位置，這應該只是計數錯誤
    另外，點擊搜尋詞時會 +1 ，點到底會加至正確的值

**Desktop (please complete the following information):**
 - Browser: Linux, Firefox Developer Edition 122.0b9

**Comment by hoothin** [comment]
正規表達式有問題，那中間不是空格，是`&nbsp;`。你得用`/[^.][0-9]{2,}[.0-9]*\s*Gi*B/`
