### ISSUE TITLE
搜索框读取问题

### ISSUE THREAD

**Issue by QiQi777iii** [hoothin/SearchJumper#111]
1. www.google.com/search
2. 在谷歌的搜索界面我禁用了学术的这个分组，导致无法读取搜索框，一直读取剪贴板的文字，例如
![image](https://github.com/hoothin/SearchJumper/assets/141505720/42efc95a-e54c-466c-bc94-7b5fa7661ece)
搜索框是你好，但是我剪贴板有东西就一直在读取剪贴板的文字，我看了基本设置界面但是没有看到有禁止读取剪贴板的字样，如果再启用学术这个分组就一切恢复正常了，请问这是一个bug还是可以进行相关设置而我没有找到。
3. 希望可以进行解答一下，谢谢了

**Comment by hoothin** [comment]
你需要添加谷歌这个引擎，告诉搜索酱如何获取关键词，当然不一定要放在学术分组。
否则搜索酱不知道当前是搜索引擎界面。只会按照普通页面的逻辑走，先检测是否有框选的文字，如果没有，则读取剪切板。

**Comment by QiQi777iii** [comment]
好的解决了谢谢您
