### ISSUE TITLE
页内查找的高亮关键词跳转的滚轮支持

### ISSUE THREAD

**Issue by YandLiu** [hoothin/SearchJumper#112]
现在是点击关键词跳到下一个高亮位置，希望可以支持鼠标滚轮跳转，这样点的快了不会触发双击动作
![image](https://github.com/hoothin/SearchJumper/assets/26127104/f2a90849-779b-4d56-bdb2-4ccaf52f8a1e)

**Comment by hoothin** [comment]
在数字区域（1/50那里）双击就没问题了，滚轮是个好建议，我有空加一下

**Comment by hoothin** [comment]
新版已经添加了滚轮切换高亮词的功能。
