### ISSUE TITLE
使用搜搜酱后，b站加载时间变长

### ISSUE THREAD

**Issue by brook12** [hoothin/SearchJumper#113]
具体表现是：
B站视频播放页面内容可以正常加载，可以正常进行各种操作。但是标签页上还会一直转圈，一般持续不到两分钟。

虽然不会影响正常的用户操作，但是有一些浏览器插件只有在网页完全加载完成后才会生效，比如我用的一个视频播放速度控制插件。

禁用搜索酱之后恢复正常。尝试单独关闭搜索页关键词高亮，没有效果。

另外有没有什么方法，可以在拖动图片时，打开其对应的超链接，而不是图片本身的地址呢？

谢谢！！

**Comment by hoothin** [comment]
仔细看说明啊。你是大陆用户吧，你需要在设置内删除被墙掉的网站（例如油管/niconico之类），否则打开 b 站时浏览器就会卡在图标加载上。
还有一种方法是在设置内开启图标缓存。这样无法访问的图标就会缓存无效状态。不会再次尝试加载。
目前指向图片时无法获取父元素链接地址，是个好建议，我待会儿加一下。

**Comment by hoothin** [comment]
新版已经把`%u`改为链接优先，你可以使用`%u`来获取图片父元素的链接，也可以在父级元素为a的时候用`%t`来继续获取图片链接。
