### ISSUE TITLE
Check one website is opened and update it

### ISSUE THREAD

**Issue by Lapse176** [hoothin/SearchJumper#115]
I am reading news in japanese and i want to search meaning of some words. I enabled "Open links in new tabs by default" function. I use deepl to translate and I want whenever I use SearchJumper, it will check if deepl tab is opened or not. If deepl tab is opened then it will update that tab to new word I search.
Example: www.deepl.com/translator#ja/en/%E4%B8%96%E7%95%8C → www.deepl.com/translator#ja/en/%E5%B9%B3%E5%92%8C
Could you add that feature? Thanks

**Comment by hoothin** [comment]
No you can't, but you can use `showTips` instead.

![image](https://github.com/hoothin/SearchJumper/assets/5361213/e8a9f7f7-d848-4ff3-812d-a34551418e0c)

```
showTips:https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&dt=bd&dj=1&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=at&sl=ja&tl=en&q=%s
<h3 style='margin: 0;'>{name}</h3>
<a style="color:red;" href="https://www.deepl.com/translator#ja/en/%s" target="_blank">Deepl</a><br>
{json.sentences.all.trans}
<br>
<font style='display: block;' color='antiquewhite'>{json.sentences.all.orig}</font>
<font style='display: block;' color='yellow'>{json.sentences.-1.src_translit}</font>
```
