### ISSUE TITLE
[功能建议]跟随鼠标位置

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [hoothin/SearchJumper#12]
小众过来，作者 niubility-plus
最大的好处是集成了右键搜索与搜索跳转，一份配置两边使用．且比右键菜单方便，比搜索跳转美观，无侵入兼容性更好．Searchenginejump 及各种修改版光荣退役

彩虹完毕提个建议

鼠标位置弹出，隐藏时完全隐藏
图标排列可以做成微软磁贴和 quicker 那样，更容易点击
或者与右键菜单同入同出，吸附在右键菜单上

**Comment by hoothin** [comment]
感谢吹捧。
鼠标跟随这个我没想好怎么搞，因为直接挪过来空间不够也不美观，做成popup search那样又要多写一套样式。所以先搁置了，哪天我有了好的点子就会加上。
喜欢微软磁贴和 quicker 的话你可以试试[ContextSearch-web-ext](https://github.com/ssborbis/ContextSearch-web-ext)，除了没有切换功能，应该和你的要求一样

**Comment by LakeishaKowalczyk** [comment]
切换功能刚需所以只能赖在这里了hhh
确实要增加很多工作量，有想做的话可以参考下面的样子

![图片](https://user-images.githubusercontent.com/14090545/179676329-1433dcf7-1307-4c45-9ca8-fa2fef2e915b.png)
![图片](https://user-images.githubusercontent.com/14090545/179676343-c10a54d1-4cb0-40b7-98c9-ae0af7e44810.png)

**Comment by hoothin** [comment]
如果是有限个站点的话还是比较好做的，但是我把4000多个书签导入进来了。上图两种UI逻辑都是不足以存放这么多内容的，必须得加上滚动条。而有了滚动条的话，为了便于定位，工具栏则是越大越好，这又与跟随鼠标减少鼠标移动的目的相悖了，除非仅限定少数站点在此显示。

如果是限定少数站点的话可以用鼠标手势绑定“第n个”展开的站点来搜索，调用代码我放在项目主页里了。
![image](https://user-images.githubusercontent.com/5361213/179677582-de5415d2-3e3d-401c-8584-a9329c1e6e6f.png)

**Comment by hoothin** [comment]
我有空时试试把鼠标拖拽手势调用这个集成进去做成一个可选项吧，我考虑了一下，只是取当前显示分类与历史站点的前面几个拼接一个九宫格显示在鼠标周围也是可行的。
感谢分享建议。

**Comment by LakeishaKowalczyk** [comment]
> 

辛苦辛苦

**Comment by hoothin** [comment]
已经加上了，设置页最底下的选项开启。内圈是当前展开站点的前6个，外圈是最近访问的前10个
![image](https://user-images.githubusercontent.com/5361213/180007205-a783c866-c6ba-400a-b9a4-c392b0ce0223.png)

**Comment by LakeishaKowalczyk** [comment]
这个效率无敌，刚刚鼠标拖一下出个轮盘惊了
