### ISSUE TITLE
脚本在必应搜索上不可用。

### ISSUE THREAD

**Issue by Nergrove** [hoothin/SearchJumper#13]
使用必应搜索的时候，不会弹出搜索工具栏。记得唯一一次可用就是在小众软件上面看到刚下载的时候，后来更新之后（不记的是哪个版本以后），就不可用了。但是使用百度和google搜索的时候，又没有任何问题，能够正常弹出搜索栏。我开始以为是和我其他插件有冲突，排查了好几次都没有发现是什么问题。而且如果是和其他软件有冲突的话，也不可能百度goole能用，必应不能用。访问域名的权限也给了。看了一下之前的issue，好像其他人也没有遇见过类似的问题。

**Comment by hoothin** [comment]
在设置里面更改bing的匹配域名，你估计用的是cn.bing吧
