### ISSUE TITLE
请问是否计划支持mac版Safari？

### ISSUE THREAD

**Issue by pencilheart** [hoothin/SearchJumper#136]
在mac版Safari安装油猴插件并导入此脚本后，搜索并未出现功能栏。但chrome测试支持。请问是否有计划支持mac版的Safari？

**Comment by hoothin** [comment]
mac 上是用的哪一个脚本管理插件？UserScript 还是 Tampermonkey？

**Comment by hoothin** [comment]
抱歉，mac 上的 Tampermonkey 是收费的，我没有买。你可以试试 UserScript，我刚测试了一下，可以正常使用

**Comment by pencilheart** [comment]
好的，感谢🙏

**Comment by pencilheart** [comment]
stay可用，感谢🙏
