### ISSUE TITLE
预览链接的问题

### ISSUE THREAD

**Issue by YandLiu** [hoothin/SearchJumper#138]
1. 其他页面正常工作，但在谷歌搜索页面不正常
2. 预览窗口出现位置与鼠标位置有关，希望能设置成固定位置，能固定就更好了
3. 在Github上，不是像其他页面一样显示出来长长的搜索条，而是就短短一条，而且预览链接点了没反应呢？

![图片](https://github.com/hoothin/SearchJumper/assets/26127104/c3459b5d-7a10-4331-89ad-03e74f99c1f6)

![图片](https://github.com/hoothin/SearchJumper/assets/26127104/c68a6506-2fff-42df-a327-e5ab916824cd)

用的Firefox+Tampermonkey+脚本，复制了这个规则，改了改预览的高度宽度和图标，别的没改
https://github.com/hoothin/SearchJumper/discussions/65

**Comment by hoothin** [comment]
我在规则的描述里有写，需要配合去 cors 扩展使用，例如 [Ignore X-Frame headers](https://chromewebstore.google.com/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe)。
你是从小众论坛过来的吧？和那个帖子里的其他扩展一样，但凡是通过 iframe 嵌入来实现功能的扩展都免不了要去除 X-Frame 头。

短短一条是因为在链接上唤出了，这些分类都是对链接生效的。在空白处唤出就是完整的了。
然后 showTips 必须点开分组，你直接在列表里点击是不会生效的。

**Comment by hoothin** [comment]
建议你把链接预览往前挪，然后直接拖拽链接来打开 showTips
如果你想要在固定位置弹出，可以这样写
```
showTips:
<style>
.search-jumper-tips{
    background: unset;
    box-shadow: unset;
    max-width: unset;
    width: auto;
    top: calc(50vh - 250px) !important;
    left: calc(50vw - 310px) !important;
}
.search-jumper-tips * {
    max-width: unset;
    width: auto;
}
.search-jumper-tips iframe{
    background: #f5f5f5e0;
    box-shadow: 0px 0px 10px 0px #000;
    width: 620px;
    height: 500px;
    resize: auto;
}
</style>
<iframe src="%t"></iframe>
```

**Comment by YandLiu** [comment]
> 需要配合去 cors 扩展使用

已经用了Ignore X-Frame headers，在谷歌搜索页面还是不正常

> 在空白处唤出就是完整的了

没明白，我想要预览链接不就得在链接上唤出这个条吗？我设置了按住Ctrl+拖拽显示圆盘，但是发现圆盘里的选项很少，没有预览链接这个功能，看脚本设置页面也没懂在哪里才能添加自己想要的功能进圆盘呢


还有个问题，预览过的链接不会进入浏览器历史记录中，希望能被历史记录记下来

**Comment by hoothin** [comment]
是的，但是GitHub这个分组有匹配，一旦匹配就会提前分组。
你可以把GitHub这个分组的匹配删除。

圆盘内容不是设置，而是调用的。
你打开设置页不是能看到四个颜色的按钮吗？它们分别代表第一个对应类别的分组，你点进去修改分组内容就能看到圆盘内容变化了。
历史记录这个可以加，我下个版本加上。

**Comment by YandLiu** [comment]
我觉得Github分组挺好的，没有删除，有没有办法可以使点击1楼第二张图上的链接预览也可以生效呢？
另外我想在Github分组直接复制一个同样的“链接预览”，但是提示不能有同样的站点URL，限制这个的原因是？

**Comment by hoothin** [comment]
可以的，你直接克隆就是了，点击分组上面那个对勾，就能看到克隆的选项。

1 楼第二张图你为什么不点开分组抽屉，而一定要在列表上点击呢？是有什么原因吗？

**Comment by YandLiu** [comment]
原来只是提示作用？我还以为直接就能点击了，囧……这样少一步更方便
另外我用空白配置测试了下，也装了Ignore X-Frame-Options，但是在Github和谷歌搜索页面上预览链接都不工作

**Comment by hoothin** [comment]
抱歉，因为安全原因，我自己不用绕过 cors 扩展，如果我上面给出的不生效，那就需要你自己去找一个了。

**Comment by YandLiu** [comment]
好的 非常感谢
装上个改CORS的扩展，谷歌搜索页面的链接预览是没有问题了，但是Github上的还是空白的，所以Github上这个应该是别的原因？

**Comment by hoothin** [comment]
错误提示是啥？如果不是 cors 的问题，那么大概率是 github 自身的内容禁止在 iframe 中显示吧

**Comment by YandLiu** [comment]
似乎都跟CORS没关？
谷歌的好像只是网卡了……晕死
Github这个，我已经启用了Ignore X-Frame-Options扩展的。看了下控制台，说是
> Content-Security-Policy：页面设置阻止读取位于 xxx 的一项资源("frame-src")。

我去AMO上搜了下CSP相关的扩展，看起来都不像是能解决这个问题的

不知道为啥MaxFocus那个扩展就能在Github上正常预览

**Comment by hoothin** [comment]
那你就重新找一个呀。
这个错误是响应头里的 Frame-Options 导致的，光删除 X-Frame-Options 肯定不够。
Max那个扩展我记得是用 `declarativeNetRequest` 把 `X-Frame-Options` `Frame-Options` 甚至还有整个 `Content-Security-Policy` 全部删掉的，而且还改了 `ALLOW-FROM`。实在是太狠，反正我是不敢用。

**Comment by hoothin** [comment]
你如果不在意安全的话，用 modheader 按我下面的图示写，和 max 效果是一样的。注意底下那个 url filter 要设定好。
![image](https://github.com/hoothin/SearchJumper/assets/5361213/cc4b3347-6af3-4924-be46-0d47f84f5f77)


不过这个已经偏题很远了。搜索酱也不是用来显示 iframe 的

**Comment by YandLiu** [comment]
感谢这么细致耐心的解答！只能说搜索酱太强大了！一个小功能就代替掉一个扩展！
现在终于明白了，Firefox默认的CSP好像比Edge严很多
Edge我去掉响应头里的`X-Frame-Options`就可以
Firefox要在about:config里新建个`security.csp.enabled`，设置为false，再搭配扩展去掉响应头里的`content-security-policy`和`X-Frame-Options`，缺一不可

**Comment by YandLiu** [comment]
现在发现又没有添加到历史记录了，最新版Firefox+最新版扩展
> 历史记录这个可以加，我下个版本加上。

另外还有个issue：预览中预览不会记为历史记录
https://github.com/hoothin/SearchJumper/issues/188
