### ISSUE TITLE
已经关闭`启用站点快捷键`下，分组切换快捷键依然生效

### ISSUE THREAD

**Issue by NHZEX** [hoothin/SearchJumper#140]
**Describe the bug**
已经把`启用站点快捷键`选项禁用了，但`当前分组内引擎切换快捷键`依然生效。

**To Reproduce**
访问谷歌搜索时按下`Ctrl + Shift + ➡`，会切换搜索引擎到百度。必须把`Ctrl`与`Shift`的勾都去除才能关闭。

**Expected behavior**
预期`启用站点快捷键`是总开关，关闭后快捷键是不生效的。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 125.0.6422.142（1.6.9）

**Additional context**

**Comment by hoothin** [comment]
多谢反馈。
启用站点快捷键是用来控制单个引擎的快捷键的，不过分组切换快捷键归它管的确更合适。现在已经修复了。

**Comment by NHZEX** [comment]
才发现，浏览器扩展标的版本是`1.6.9`，但仓库版本已经是`1.8.x`了

**Comment by hoothin** [comment]
😅两个不是一样的版本号，user.js 是油猴版，扩展版的 1.6.11 相当于油猴版的 1.8.8。
内容都是一样的，只是扩展版多了右键菜单，配置页放在了本地，而油猴版可以支持在任意页面用 javascript: 格式的小书签来 eval 执行代码。如果用不到 eval ，扩展版的安全性更高。

**Comment by NHZEX** [comment]
明白了，等发版，Thanks~
