### ISSUE TITLE
如何固定拖拽圆盘中预览链接出现的位置/如何快速调用预览链接？

### ISSUE THREAD

**Issue by YandLiu** [hoothin/SearchJumper#146]
不同网站上，预览链接在不同位置，无法盲拖拽预览，不够丝滑，有什么办法将它的位置固定住？另外有没有什么办法快速调用这个功能？比如我想设定个快捷键，鼠标悬浮在链接上时我按下快捷键就直接预览
其实我用Ctrl+拖拽就是为了预览链接功能，有啥办法Ctrl+任意方向拖拽无需拖到特定位置就能预览？

下面分别是Github、小众、其他一些网站上的“预览链接”出现的位置
![图片](https://github.com/hoothin/SearchJumper/assets/26127104/1b9c2480-96d8-4e9a-8bcb-793b8e707d51)

![图片](https://github.com/hoothin/SearchJumper/assets/26127104/6883836a-1fa6-45a4-8a13-3056e50eae20)

![图片](https://github.com/hoothin/SearchJumper/assets/26127104/edec95c6-fe3b-4280-8fd2-2632225201a3)

**Comment by hoothin** [comment]
1 关闭“置顶当前分组”
2 把 github 分组拖到当前网页分组后面
3 把小众软件评论这个引擎删掉

另外不建议你直接完全导入我分享的引擎，你挑几个你用得到的导入就可以了

**Comment by hoothin** [comment]
脚本版已经更新 1.9.3，添加了 showTips 的快捷键支持，现在鼠标悬浮后按快捷键可以唤出 showTips 了

**Comment by YandLiu** [comment]
具体该如何做呢？我看了下设置页面，没有相关的设置
尝试鼠标悬浮到链接上时按下Ctrl，也没有反应

**Comment by hoothin** [comment]
要有按键的，不能只有修饰键
