### ISSUE TITLE
划词拖拽搜索能否设置成在新标签页打开

### ISSUE THREAD

**Issue by lurui45** [hoothin/SearchJumper#15]
目前划词拖拽搜索默认在原网页打开，没有新标签页打开的设置。而且希望能自由定制划词搜索的选项，因为我发现内圈和外圈很多时候都是重叠的。

**Comment by hoothin** [comment]
+ 按住ctrl拖入新标签页打开
+ 按住alt拖入新窗口打开
+ 按住ctrl+alt拖入隐身标签页打开

这些逻辑都是通用的。

圆盘内容原本就不是写死的，可以随便自定义。
内圈是当前分类的前6个，你把需要的内容移动到当前分类的前6个就行了，外圈是你最近使用的10个历史站点。

**Comment by lurui45** [comment]
> 是否新标签页打开是跟随你自己定义的分类走的，比如文字就去你的第一个划选搜索分类里设置打开方式
> 
> * 按住ctrl拖入新标签页打开
> * 按住alt拖入新窗口打开
> * 按住ctrl+alt拖入隐身标签页打开
> 
> 这些逻辑都是通用的。
> 
> 圆盘内容原本就不是写死的，可以随便自定义。 内圈是当前分类的前6个，你把需要的内容移动到当前分类的前6个就行了。分类指向的是你配置里的第一个“文字”“图片”“链接”分类。 外圈是你最近使用的10个历史站点。

理解了，因为我的使用场景是比如在看文章时发现一个关键字想搜索淘宝或者谷歌，我之前的习惯是设定选中关键词左滑百度上滑淘宝右滑谷歌这样，现在用这个插件是拖拽关键字出现的圆盘内圈都是站内搜索，其实用到站内搜索的场景并不频繁。所以我希望能自由设定内圈的应用，固定起来，每个分类最常用的我都放一个，有搜索，有购物，有图片。

**Comment by hoothin** [comment]
可以把淘宝、谷歌都克隆快捷方式到站内搜索，并且移动到前6个，克隆后图片url都是跟着主站点走的
