### ISSUE TITLE
应该添加一个高亮关键词超时机制

### ISSUE THREAD

**Issue by shallmas** [hoothin/SearchJumper#156]
商店版、脚本版均为最新
谷歌搜索如下关键词
"aars1"  bladder  cancer gse
进入第一个结果
https://www.reading.ac.uk/bioinf/downloads/PINOT_scripts/conversion-table.txt
可以看到有很多的匹配项，导致网页卡顿甚至崩溃。
我很喜欢这款软件，但我觉得它最基本的功能之一，搜索后高亮相关的关键词，仍有改进空间
应该针对这种大量匹配的情况做出回应，设置一个黑白名单，或者触发匹配的最大值

**Comment by hoothin** [comment]
设置页的页内高亮 tab 有黑名单。
卡死不一定是因为量大，也有可能是因为页面 js 检测到变更立即还原导致的死循环（例如 alternativeto.net），此时只有禁用高亮一种办法。
高亮加节流倒是不难，但等待的过程中可能会出现新插入的元素。而执行时的旧数据就可能被污染（例如已被删掉或内容变得不匹配）。
所以容我再想想吧。
