### ISSUE TITLE
划词磁贴中历史站点不显示

### ISSUE THREAD

**Issue by zhaocai** [hoothin/SearchJumper#157]
**Describe the bug**
历史站点在划词磁贴中不显示

**Screenshots**
如下图，历史站点不显示，显示的就是“划词搜索”中的图标。
![image](https://github.com/user-attachments/assets/0182081c-3539-45ff-b985-533fdb612a18)

而在全部展开模式，可以看到历史站点是有记录的。
![image](https://github.com/user-attachments/assets/4cb96840-53b3-4741-9891-0eb67e8cd6f9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge / Arc browser
 - Version: latest from greasefork

**Comment by hoothin** [comment]
目前的逻辑是需要满足以下两个条件才会插入历史站点：
1. 指向与当前分类相同，例如指向链接的历史引擎不会出现在文本分类。
2. 当前分类中没有，例如当前分类已有引擎 a，历史引擎 a 就会被忽略。

这里的条件 1 有点问题，因为普通分类的指向和划词分组的分类是不一样的。我已经更新了一版，改成了普通分类的历史引擎也会插入划词分组。

**Comment by zhaocai** [comment]
> 目前的逻辑是需要满足以下两个条件才会插入历史站点：
> 
> 1. 指向与当前分类相同，例如指向链接的历史引擎不会出现在文本分类。
> 2. 当前分类中没有，例如当前分类已有引擎 a，历史引擎 a 就会被忽略。
> 
> 这里的条件 1 有点问题，因为普通分类的指向和划词分组的分类是不一样的。我已经更新了一版，改成了普通分类的历史引擎也会插入划词分组。

更新完成后已经能够正常使用了，非常开心，感谢及时进行的修复工作。
