### ISSUE TITLE
Seek help for rule of 「deepseek api调用」

### ISSUE THREAD

**Issue by Ameryou** [hoothin/SearchJumper#158]
大佬您好，下面是小弟的问题：
「deepseek api调用」
1.官方文档：
https://platform.deepseek.com/api-docs/zh-cn/
2.模拟大佬您gemini的写法叫ai写了下，但自己不懂代码，有环节出错了。大佬有空的话能帮写一下吗，就类似这种：
showTips:https://api.deepseek.com/chat/completions?api_key=%template{请输入 DeepSeek API 密钥}%&%p{%7B%22model%22%3A%22deepseek-chat%22%2C%22messages%22%3A%5B%7B%22role%22%3A%22user%22%2C%22content%22%3A%22请解释一下：%su%22%7D%5D%2C%22stream%22%3Afalse%7D}
<style>
.search-jumper-tips {
  font-size: initial;
  line-height: normal;
  font-weight: normal;
}
</style>
<pre class="markdown">
{json.choices[0].message.content}
</pre>

**Comment by hoothin** [comment]
gemini 和 openapi 格式不一样，你应该参考 max api 那个规则，我放在下面吧
```
showTips:https://api.deepseek.com/chat/completions%p{{ {  "model": "deepseek-chat", "messages": [{"role": "user", "content": "请请解释下面的内容：%s"}], "temperature": 0.7, "stream": true} }}#headers{"Content-Type": "application/json","Authorization": "Bearer %template{DeepSeek API 密钥}"}#stream
<style>
.search-jumper-tips {
    font-size: initial;
    line-height: normal;
    font-weight: normal;
}
</style>
<pre class="markdown" data-paste>
{json[all].choices[0].delta.content}
</pre>
```

**Comment by Ameryou** [comment]
谢谢您
