### ISSUE TITLE
没搞明白怎么导入设置

### ISSUE THREAD

**Issue by lurui45** [hoothin/SearchJumper#16]
还是没搞明白怎么导入设置。
我尝试将导出设置下面的源码粘贴到另外一台电脑插件里面的自定义样式栏里面，也没有导入的按钮，怎么生效呢？

**Comment by hoothin** [comment]
啥？自定义样式栏？我没有写过那个呀。

你是要导入啥设置？[我的配置](https://github.com/hoothin/SearchJumper/issues/1)直接点击就能导入。
如果你说的是自己备份的配置，那么点击设置页左侧的快捷拨号里的导出为json，再到另一台电脑导入json就行了。或者也可以学我在issue里用pre标签包裹你的配置

**Comment by lurui45** [comment]
感谢，眼拙，没看见右边有个＋号

**Comment by hoothin** [comment]
确实可能看不到，我已经把默认状态改成展开了
