### ISSUE TITLE
怠惰小说下载器导致B站评论区无法选中文字

### ISSUE THREAD

**Issue by benzBrake** [hoothin/SearchJumper#166]
**Describe the bug**
只要启用 怠惰小说下载器 脚本，B站评论区无法选中文字

**To Reproduce**
1.启用 怠惰小说下载器
2.前往B站评论区
3.随便选择评论文字

**Expected behavior**
正常选中文字

**Screenshots**
无

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 128.1.0esr

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
发错地方了吧😓，这是因为阿拉伯文字
