### ISSUE TITLE
百度页面内使用搜索框，文字部分占满全屏

### ISSUE THREAD

**Issue by Jackxwb** [hoothin/SearchJumper#17]
百度搜索页面内修改搜索内容二次搜索后，搜索酱的文字部分会占满全屏（疑似样式丢失了），控制台未发现报错

https://user-images.githubusercontent.com/34720403/182811305-28f1132c-cf3d-41a8-b507-5694d3d2b5d6.mp4

**Comment by hoothin** [comment]
修复了
