### ISSUE TITLE
在百度贴吧网页端，帖子中的头像和各楼层内的评论显示异常

### ISSUE THREAD

**Issue by TheWiseWolfHolo** [hoothin/SearchJumper#171]
## 复现
- 在百度贴吧网页端的任意帖子中，保持`SearchJumper`启用即可复现；
- 禁用拓展并刷新后，**头像**与各楼层内的**评论**恢复正常。

**Fig1 头像异常状态**
![图片](https://github.com/user-attachments/assets/a679abf1-709b-46fe-a6a1-840482da51d3)
**Fig2 楼层内的评论异常状态**
![图片](https://github.com/user-attachments/assets/12657281-08e4-4573-b766-571b9246bcf1)

## 运行平台
- Windows 11 
- Firefox
  - 版本 130.0.1
  - 版本 ID 20240913135723
 
## 补充
- 各主楼层均无影响，只影响楼层内的评论；
- 刷新页面会导致当前页内的**头像**与**评论**恢复正常，继续浏览其余部分，对应的**头像**与**评论**依旧显示异常。

**Comment by hoothin** [comment]
![image](https://github.com/user-attachments/assets/bb2204fe-19d7-4429-96a5-2203cc1ad23c)
测试没重现，检查一下本机的其他扩展，看看是不是冲突了

**Comment by TheWiseWolfHolo** [comment]
**感谢回复!!!**
## 目前启用拓展状态
![图片](https://github.com/user-attachments/assets/8e4e15b9-d6c2-48ee-b867-1c7596bde557)
- 其余禁用只启用一个拓展仍是如此。
## 完整设置导出
[searchJumper_2024-9-23_115533.json](https://github.com/user-attachments/files/17092537/searchJumper_2024-9-23_115533.json)
- 您看下这是我导出的`完整设置`，可能会有帮助。

**Comment by hoothin** [comment]
是因为图标加载拖慢了页面加载，可以关闭 `总是显示搜索条` 或者开启 `缓存图标`

**Comment by TheWiseWolfHolo** [comment]
非常感谢!解决了

**Comment by hoothin** [comment]
说错了，应该是`不隐藏并且收缩页面`造成的，贴吧页面如果 body 的 position: absolute; 就会报错。

**Comment by TheWiseWolfHolo** [comment]
- 重新打开`总是显示搜索条`
- `不隐藏并且收缩页面`改为`未设置`
### 结果
**头像**与楼层内**评论**仍显示正常

**非常感谢，完美解决**🙏🙏
