### ISSUE TITLE
请教如何添加“豆包”和“Kimi”

### ISSUE THREAD

**Issue by sixrui** [hoothin/SearchJumper#187]
无法用ctr+alt+点击获取到豆包和kimi的搜索规则
好像和普通搜索引擎的规则不一样。
请教如何添加

**Comment by hoothin** [comment]
https://github.com/hoothin/SearchJumper/discussions/65

这里有kimi，直接导入就能用
自行添加可以用扩展工具栏图标右键里的“添加引擎”，点击手型图标来添加

**Comment by sixrui** [comment]
> #65
> 
> 这里有kimi，直接导入就能用 自行添加可以用扩展工具栏图标右键里的“添加引擎”，点击手型图标来添加

感谢，kimi已经成功添加，但是豆包搞不定，用的录制方法添加的，卡在最后一步， 关键字输完后不点击搜索。
方便的话看一下问题出在哪
https://www.doubao.com/chat/search#p{#sticky-header > div.input-V1SgxX:nth-of-type(2) > div.input-area-_mgT8h:nth-of-type(1) > div.flex:nth-of-type(1) > div > textarea.semi-input-textarea.semi-input-textarea-autosize=%s&click(#flow-end-msg-send > span.semi-button-content > span.semi-icon.semi-icon-default > svg)}

**Comment by hoothin** [comment]
电脑不在身边，你在点击之前添加 sleep 动作试试

**Comment by sixrui** [comment]
> 电脑不在身边，你在点击之前添加 sleep 动作试试

试了添加最多到500ms，还是没反应，等您有空试试吧

**Comment by hoothin** [comment]
试试这个`https://www.doubao.com/chat/search#p{textarea.semi-input-textarea=%s&click(#flow-end-msg-send)}`

**Comment by sixrui** [comment]
> 试试这个`https://www.doubao.com/chat/search#p{textarea.semi-input-textarea=%s&click(#flow-end-msg-send)}`

解决了 谢谢
