### ISSUE TITLE
能否允许关闭拖动搜索的外圈

### ISSUE THREAD

**Issue by lurui45** [hoothin/SearchJumper#19]
不怎么用得到拖到搜索轮盘的外圈，因为外圈经常变会干扰拖动习惯，还经常失误拖到外圈。

**Comment by hoothin** [comment]
如果给个选项，外圈接着放内圈放不下的内容呢？

**Comment by lurui45** [comment]
> 如果给个选项，外圈接着放内圈放不下的内容呢？

那也很好啊，我个人来说拖动是属于最常用的搜索方式，肌肉记忆，上下左右分别搜索四个最常用的，如果需要进一步搜索，我不如右键长按唤出完整的浮动条了，所以对我来说拖动的时候不希望判断二级轮盘。

**Comment by hoothin** [comment]
好的，那我给个选项直接隐藏外圈吧

**Comment by 754932057** [comment]
> 如果给个选项，外圈接着放内圈放不下的内容呢？

您好，攻城狮，我想自己能设置内圈，固定自己习惯常用的搜索能行？如果不难敲代码请采纳我的意见，谢谢啦！

**Comment by hoothin** [comment]
> > 如果给个选项，外圈接着放内圈放不下的内容呢？
> 
> 您好，攻城狮，我想自己能设置内圈，固定自己习惯常用的搜索能行？如果不难敲代码请采纳我的意见，谢谢啦！

好好看说明啊你(～￣(OO)￣)ブ，本来就是自己设置的啊

**Comment by 754932057** [comment]
> > > 如果给个选项，外圈接着放内圈放不下的内容呢？
> > 
> > 
> > 您好，攻城狮，我想自己能设置内圈，固定自己习惯常用的搜索能行？如果不难敲代码请采纳我的意见，谢谢啦！
> 
> 好好看说明啊你(～￣(OO)￣)ブ，本来就是自己设置的啊

实在很抱歉，我是昨天才开始使用这个插件的，具体设置我还不太清楚，请您指导下可以？又或者是有一个详细的教程也行，谢谢攻城狮啦

**Comment by hoothin** [comment]
@754932057 可以参考 #15

**Comment by hoothin** [comment]
外圈隐藏的选项已经加上了。你试试

**Comment by lurui45** [comment]
Good! 开启了之后外圈是透明灰色的。以后有时间的话，考虑彻底隐藏外圈

**Comment by hoothin** [comment]
试过完全隐藏，就是有点丑，另外考虑到轮盘太小的话可能一不小心就拖到圈外导致关闭了。
