### ISSUE TITLE
在nature.com上页内查找栏显示有问题

### ISSUE THREAD

**Issue by YandLiu** [hoothin/SearchJumper#191]
当焦点在页内查找栏时（包含初始按下快捷键唤出），页面自动滚动到底部，并且查找栏只显示短短一条

示例网址：https://www.nature.com/articles/s41408-022-00765-8

焦点在栏里：
![image](https://github.com/user-attachments/assets/aa6f614e-b366-45c0-93e4-2e435f0e905e)

焦点不在栏里：
![image](https://github.com/user-attachments/assets/0f0fbd4b-656f-454f-8b7e-5a633a731dea)

**Comment by hoothin** [comment]
感谢反馈，已经修复
