### ISSUE TITLE
屏蔽元素功能实在太棒了

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [hoothin/SearchJumper#22]
一直很需要的全网站屏蔽功能
相信很多人都有这个需求，属于重磅特性了，可以重点介绍与增强

两个小建议
使用单独的设置窗口．从浏览器工具栏进入，或者页内查找右边再加一个标签就好
可以用元素选择器限定区域．有时同一个屏蔽目标，会同时出现在页面不同位置，然后需要设置不同的深度，这样就可以分开设置了
~~还有什么来着，打上面的字的时候写着写着忘记了，我丢~~

**Comment by hoothin** [comment]
不错的建议，mark了，我试试在下个版本实现一下
