### ISSUE TITLE
是否有隐藏某搜索引擎|分类的选项

### ISSUE THREAD

**Issue by ted423** [hoothin/SearchJumper#25]
比如目前不用这个引擎就先隐藏，以后要用再打开。
人总是会变得(

另外就是有些引擎可能暂时性的不能用。

感觉这样自定义性会比较高

**Comment by hoothin** [comment]
match填0就是隐藏

**Comment by hoothin** [comment]
哇，你是searchEngineJump-NextStage的作者吗？

**Comment by ted423** [comment]
以前瞎搞de脚本,眼瞎，没看到
