### ISSUE TITLE
在 serx.ml 显示异常

### ISSUE THREAD

**Issue by wordpure** [hoothin/SearchJumper#26]
在 [serx.ml](https://serx.ml/)，搜索酱的添加搜索引擎表单、轮盘、下拉列表无法正常显示，FontAwesome 图标显示乱码。

![图片](https://user-images.githubusercontent.com/68013962/194465327-a2144fe3-ab0a-4136-940c-bd7712757f7e.png)

![图片](https://user-images.githubusercontent.com/68013962/194465593-967753c5-6bdd-44af-b88f-a8bddcf2c52a.png)

![图片](https://user-images.githubusercontent.com/68013962/194466541-cb659940-ffe5-472b-8d95-94da16ebc86b.png)

使用 Header Editor 移除所有请求的 CSP 标头后，轮盘、下拉列表和 FontAwesome 图标可以正常显示。添加表单除了图标部分的显示也正常。

![图片](https://user-images.githubusercontent.com/68013962/194467106-24c9d81f-1555-4b93-9365-a107d0b7f092.png)

浏览器：Firefox 106

脚本管理器：Violentmonkey 2.13.1

**Comment by hoothin** [comment]
感谢反馈！
换用Tampermonkey就行了，暴力猴的GM.addstyle是直接插入head，没法绕过CSP限制

**Comment by wordpure** [comment]
> 暴力猴的GM.addstyle是直接插入head

暴力猴 2.13.1 增加了对 [GM_addElement](https://violentmonkey.github.io/api/gm/#gm_addelement) 的支持，不知道能不能用这个 API 解决？

![图片](https://user-images.githubusercontent.com/68013962/194472790-b3d42c18-8ccc-4cb0-a395-3932e2c50c77.png)

另外，改用 Tampermonkey 之后添加搜索引擎表单图标部分的显示还是有问题。

![图片](https://user-images.githubusercontent.com/68013962/194471050-3aeb731a-50d3-4214-bc95-566b6044ec38.png)

切换到 Edge 之后可以正常显示。或许还是 Firefox 的锅？

![图片](https://user-images.githubusercontent.com/68013962/194471139-e5d186ed-7ef1-4311-b479-210300ca65a9.png)

**Comment by hoothin** [comment]
因为火狐没有overlay😄，我换成auto了。更新下搜索酱就行了。

GM_addElement我来试试，不过应该也是不行的，因为SearXNG、鸭鸭、还有火狐扩展中心的安全策略都是禁止inline css执行，即是说就算是网页本身的inline css代码都不能执行。

**Comment by wordpure** [comment]
顺便提几个关于添加表单的建议。

1. 描述、地址和图标能不能改成多行文本框？
	这三个字段查看、编辑的频率比较高，横向滚动不太方便。
2. 能不能把搜索词正则、匹配 URL、打开选项和站点编码也加进去？
	这几个选项还是挺常用的。
3. 「设置 - 搜索引擎 - 编辑站点」的「编辑」按钮，改成「保存」或 「确定」会不会比较好？
	在编辑界面还叫「编辑」真的好奇怪啊🤣

![图片](https://user-images.githubusercontent.com/68013962/194473884-ce47390a-ebb2-47ec-b30e-cecfc85f4482.png)

![图片](https://user-images.githubusercontent.com/68013962/194476899-e05e67e5-7271-4f68-b590-15019317ca2f.png)

**Comment by wordpure** [comment]
> 因为火狐没有overlay😄，我换成auto了。更新下搜索酱就行了。

更新后正常了。

> GM_addElement我来试试，不过应该也是不行的，因为SearXNG、鸭鸭、还有火狐扩展中心的安全策略都是禁止inline css执行，即是说就算是网页本身的inline css代码都不能执行。

感谢。

不行我就改用 Tampermonkey 了，省心省力😂

**Comment by hoothin** [comment]
我试了下addElement，效果和addStyle一样，在暴力猴下还是绕不过内联样式的安全限制😓

搜索词、匹配url、站点编码这些是自动识别的。一般情况下不用配置，所以我没加到快捷添加里去。我看看要么再加一个详细模式切换按钮。

**Comment by wordpure** [comment]
搜索参数这里，能不能根据网页语言切换显示内容？

现在不管网页语言是简体中文还是英文，框选的这两个地方显示的内容都是固定的，和界面其他地方不太搭。

![图片](https://user-images.githubusercontent.com/68013962/194480377-2a282f14-a053-4511-93f7-807480bbec6b.png)

![图片](https://user-images.githubusercontent.com/68013962/194480416-ec96ce5f-6a1c-4396-aec2-cb4ce3ef9169.png)

**Comment by wordpure** [comment]
> 我试了下addElement，效果和addStyle一样，在暴力猴下还是绕不过内联样式的安全限制😓

那只能换 Tampermonkey 了😂

> 搜索词、匹配url、站点编码这些是自动识别的。一般情况下不用配置，所以我没加到快捷添加里去。我看看要么再加一个详细模式切换按钮。

感谢🌹

**Comment by hoothin** [comment]
完成了

**Comment by wordpure** [comment]
> 3\. 「设置 - 搜索引擎 - 编辑站点」的「编辑」按钮，改成「保存」或 「确定」会不会比较好？
>         在编辑界面还叫「编辑」真的好奇怪啊🤣
> 
> ![图片](https://user-images.githubusercontent.com/68013962/194476899-e05e67e5-7271-4f68-b590-15019317ca2f.png)

大佬能否考虑下这个建议？
