### ISSUE TITLE
配置和导入的一些问题

### ISSUE THREAD

**Issue by wordpure** [hoothin/SearchJumper#27]
导入按钮的设计有点奇怪，似乎只在纵向内容完全显示时展示在代码块右上方，其实时刻是嵌入到滚动条底部可见区域的右上方。

而且直接点击代码块也会询问是否导入😂

![图片](https://user-images.githubusercontent.com/68013962/195397266-2849c24c-931e-413d-b511-a99f7ba6da37.png)

![图片](https://user-images.githubusercontent.com/68013962/195397006-64d86e8a-119b-47e6-96b4-58ab504d8e18.png)

![图片](https://user-images.githubusercontent.com/68013962/195397064-44a19a5f-606f-4088-b9d4-45ced4682db8.png)

![图片](https://user-images.githubusercontent.com/68013962/195397078-9d34cf46-5b61-41f2-bd2c-067ba36248e3.png)

**Comment by wordpure** [comment]
默认配置里很多搜索引擎的 URL 似乎都是从很久以前一直继承下来的，用的还是 http，现在或许可以更新为 https？

![图片](https://user-images.githubusercontent.com/68013962/195402399-1b75c62c-9c1d-40bb-81d5-4ad9d8baa9b0.png)

**Comment by hoothin** [comment]
感谢分享idea，又是一个之前偷懒没做的😅

**Comment by wordpure** [comment]
> 不过你截图里的pre块滚动条是怎么出现的呀？我在firefox和chrome都没看到

我的锅，反馈之前没有禁用其他扩展😂

这个是 [Refined Github](https://github.com/refined-github/refined-github) 增加的一个特效，没有这个扩展的话代码块会显示全部内容，嵌入按钮也可以正常显示。

**Comment by hoothin** [comment]
好的，我装个看看能不能兼容一下

**Comment by hoothin** [comment]
抽空把筛选导入加好了，另外 Refined Github 也兼容了，你试试呢😀

**Comment by wordpure** [comment]
> 另外 Refined Github 也兼容了，你试试呢😀

简直完美，感谢大佬👍

> 抽空把筛选导入加好了

还有几个小建议，希望大佬能考虑下。

1. 希望能区分「筛选」界面分类的展开、收起状态。
	第一次看到「筛选」界面的时候，我还以为只能筛选分类，好半天才反应过来，可以点击展开分类筛选搜索引擎🤣
	
	![图片](https://user-images.githubusercontent.com/68013962/196013835-abb11ad1-62ff-45e8-a2fe-977d694742bf.png)
2. 希望能加个「展开/收起全部」的按钮，并记忆最后的展开/收起状态。
3. 筛选导入时，希望 URL 判定不要区分 http 和 https。
	
	![图片](https://user-images.githubusercontent.com/68013962/196014020-6585d8d2-293d-4abe-a245-d17e88c94b80.png)
4. 导入时，如果该分类下已有同名搜索引擎，自动在名称后添加后缀，以避免出现同名搜索引擎。
	![图片](https://user-images.githubusercontent.com/68013962/196014167-78c0b772-07d0-4ad2-8522-ccacd797c212.png)
5. 希望能自定义每个搜索引擎的分类。
	即使是同一类的搜索引擎，不同人也有不同的命名方式，如果直接沿用分享时的分类名称，可能使同一类型的搜索引擎分到不同名称的分类下面。
	一个特别突出的例子： [search engine jump for academic 搜索引擎跳转(学术版)规则转换](https://github.com/hoothin/SearchJumper/issues/14) 🤣
	
![图片](https://user-images.githubusercontent.com/68013962/196014580-888fa989-30f9-43c9-91f5-91b51b10ffa0.png)

**Comment by hoothin** [comment]
感谢提供这么多好建议！我待会儿加上。
你截图用的是什么环境呀？导入分类怎么会没有下拉箭头呢

**Comment by wordpure** [comment]
> 你截图用的是什么环境呀？导入分类怎么会没有下拉箭头呢？
> 
> 我在火狐下测试是这样子的 ![image](https://user-images.githubusercontent.com/5361213/196026657-8bfaa349-8ba4-4dd9-9c37-4ceb38f25229.png)

应该是我之前改到了 Firefox 的某个设置项😂，新建一份配置文件之后就可以正常显示下拉箭头了。

![图片](https://user-images.githubusercontent.com/68013962/196034318-2ec36990-9a55-43de-90c8-5d13c50843fe.png)

**Comment by hoothin** [comment]
好的，你提到的几点都已经更新完毕啦^^

**Comment by wordpure** [comment]
感谢大佬🌹

感觉有两点可以再优化下。

1. 只在重命名结果不是空值的情况修改分类名称。
	现在点击取消会将当前分类重命名为空。
	
	![图片](https://user-images.githubusercontent.com/68013962/196041206-80882e6a-4af4-4766-9ff1-5a73ba21829f.png)
2. 导入后点击通知可以打开配置页面。
	
	![图片](https://user-images.githubusercontent.com/68013962/196041300-165cab6b-00c2-49e9-b3df-d36d6347c2a9.png)

**Comment by hoothin** [comment]
你真细心呀，已经修复了。
期待你下一次的建议。

**Comment by wordpure** [comment]
> 期待你下一次的建议。

还有一些其他方面的想法，等整理好了再提个 issue😁
