### ISSUE TITLE
和网页中代码框冲突？

### ISSUE THREAD

**Issue by H-Tung** [hoothin/SearchJumper#29]
在这个网页上：https://www.cnblogs.com/cstylex/p/Rime_on_Linux_Android_Mac_Windows_iOS_sync.html
代码框出现了如下内容
`<mark class="searchJumper" data-content="sync" style="background: rgb(233, 30, 99); color: rgb(255, 255, 255);">sync</mark>_<mark class="searchJumper" data-content="dir" style="background: rgb(0, 188, 212); color: rgb(255, 255, 255);">dir</mark>: /media/sda5/<mark class="searchJumper" data-content="rime" style="">Rime</mark>user/<mark class="searchJumper" data-content="sync" style="background: rgb(233, 30, 99); color: rgb(255, 255, 255);">sync</mark>`

但我使用简悦进入阅读模式时是正常渲染的

**Comment by hoothin** [comment]
感谢反馈，修复了
