### ISSUE TITLE
可否增加自动收起工具条的功能

### ISSUE THREAD

**Issue by tjsky** [hoothin/SearchJumper#3]
不需要持续展开工具条
![_20220521174901](https://user-images.githubusercontent.com/7272911/169645995-579fb245-980e-4e96-add7-a29d68085bbe.png)
可否增加鼠标焦点从工具条移开后，延迟2000~5000后自动收起工具条会更好一点

**Comment by hoothin** [comment]
感谢建议，这个我写成配置项吧

**Comment by hoothin** [comment]
配置项已经加上了，你试试
