### ISSUE TITLE
希望支持IOS版本的safari浏览器

### ISSUE THREAD

**Issue by SONGjiemo** [hoothin/SearchJumper#32]
IOS已经有了支持油猴脚本的客户端。我希望支持IOS。

**Comment by hoothin** [comment]
应该支持的吧？我在[userscripts](https://apps.apple.com/cn/app/id1463298887)上测试过

**Comment by SONGjiemo** [comment]
> 应该支持的吧？我在[userscripts](https://apps.apple.com/cn/app/id1463298887)上测试过

我这边死活显示不了、问题在那里呢。我用电脑在百度、必应等等搜索左边都有脚本。手机上就是没有

**Comment by hoothin** [comment]
那可能又有哪个地方不兼容ios了吧，我晚些时候看下

**Comment by hoothin** [comment]
在ipad上测了下，ok了

**Comment by SONGjiemo** [comment]
> 在ipad上测了下，ok了

时没有这个bug还是什么意思
