### ISSUE TITLE
侧边栏UI能改类似探索者小舒这样伸缩的吗?

### ISSUE THREAD

**Issue by Noah1995** [hoothin/SearchJumper#33]
1丶侧边栏想要在[探索者小舒](https://chrome.google.com/webstore/detail/%E6%8E%A2%E7%B4%A2%E8%80%85%E5%B0%8F%E8%88%92-%E5%BC%BA%E5%A4%A7%E5%BF%AB%E6%8D%B7%E7%9A%84%E4%BE%A7%E6%A0%8F%E6%90%9C%E7%B4%A2%E5%88%87%E6%8D%A2%E5%B7%A5%E5%85%B7/lcalpcoppmdamffdmmchmadbpaoibaep)基础上增强
只显示图标的时候默认可以不遮挡页面(就是edge侧边栏标签一样) 
探索者小舒实在太卡了不想用了...

https://user-images.githubusercontent.com/25548230/202530358-299609b6-ceb9-498b-902d-06c2c1519a6b.mp4

2丶类似[侧边翻译](https://github.com/EdgeTranslate/EdgeTranslate)的收缩页面功能
它还能拖拽出来...
不过不知道脚本会比拓展难实现吗?
还有脚本能否实现保存设置不用刷新页面全部网页都生效?
如果不行的话最好能开发扩展吧...
不是说2023年不一定禁止用油猴脚本吗?

https://user-images.githubusercontent.com/25548230/202529016-3c792267-419c-462d-aed5-2a64e8407f8d.mp4

**Comment by hoothin** [comment]
建议去尝试 [ContextSearch-web-ext](https://github.com/ssborbis/ContextSearch-web-ext)

**Comment by Noah1995** [comment]
> 建议去尝试 [ContextSearch-web-ext](https://github.com/ssborbis/ContextSearch-web-ext)

我试过了这个太复杂且不好用
离searchbar和Selection Search差很远...

**Comment by Noah1995** [comment]
其他ui改不改不算特别重要...
那个收缩页面不遮挡内容的功能很重要啊
可以在设置里或者界面加个固定开关切换...
