### ISSUE TITLE
【建议】添加选项-点击分组按顺序切换该分类下的引擎

### ISSUE THREAD

**Issue by Noah1995** [hoothin/SearchJumper#36]
目前左键和中键都是打开抽屉
如果可以的话做成自定义选择
万一以后有其他功能方便添加

分组左键点击
1丶打开抽屉 
2丶切换引擎
3丶批量打开
4丶编辑分组

分组中键点击
1丶打开抽屉 
2丶切换引擎
3丶批量打开
4丶编辑分组

分组右键点击
1丶打开抽屉 
2丶切换引擎
3丶批量打开
4丶编辑分组

**Comment by hoothin** [comment]
暂时没空，请不要再新开issue了

**Comment by Noah1995** [comment]
> 暂时没空，请不要再新开 issue 了

好的...
有个划词的问题...
跳转引擎重新划词会导致之前跳转的词丢失...
请记忆住跳转时候文字...
我拿searchbar演示...

https://user-images.githubusercontent.com/25548230/202855911-122c422a-ca6e-4840-a545-37cb5b3c5670.mp4

**Comment by Noah1995** [comment]
https://www.hoho.tv/vod/search.html
好像是这个网站的问题吗?

**Comment by Noah1995** [comment]
其他网站好像没问题...

是不是post引擎的问题?
以为不显示图标...
我做了站点 URL 匹配它显示了...
但是无法继承跳转词汇吗?

**Comment by Noah1995** [comment]
https://user-images.githubusercontent.com/25548230/202859941-a2b6a3e9-b228-48d5-939b-f6638d420cdd.mp4

**Comment by hoothin** [comment]
感谢反馈，的确是 post 的问题。
不过我得说一句，我不喜欢你这类的用户，你的行文以及使用理念令我不适。因此还是建议你去用 selection search 或者 context search ext 并去为它们提建议或者贡献。

**Comment by Noah1995** [comment]
> 感谢反馈，的确是 post 的问题。 不过我得说一句，我不喜欢你这类的用户，你的行文以及使用理念令我不适。因此还是建议你去用 selection search 或者 context search ext 并去为它们提建议或者贡献。

好吧下次说话注意一点...
还有个bug...
设置【不隐藏并且收缩页面】
百度搜索无法滚动
其他网站目前没问题
![image](https://user-images.githubusercontent.com/25548230/202892677-c535e316-7da2-4611-b8bb-aa9f79246ee8.png)
