### ISSUE TITLE
鼠标右键弹窗

### ISSUE THREAD

**Issue by haygcao** [hoothin/SearchJumper#37]
![image](https://user-images.githubusercontent.com/29725483/203584485-da46a9d0-6167-4208-8540-c30ac65eb2a7.png)
![image](https://user-images.githubusercontent.com/29725483/203584311-825c173b-0ef8-4722-b570-a77cca097a18.png)

这个选项能不能单独分开，我不知道是我得chrome 浏览器得愿意还是怎么回事，我就是想单纯得右键新标签打开，然后就跳出第一张图，我尝试把延迟设置得高一点还是不行，但是edge 开始没这个问题，后来两边也出现了

**Comment by hoothin** [comment]
请整理语言，描述清楚具体重现步骤
