### ISSUE TITLE
【bug】百度搜索无法滚动页面

### ISSUE THREAD

**Issue by Noah1995** [hoothin/SearchJumper#38]
设置【不隐藏并且收缩页面】...
当界面呼出时...
百度搜索页面无法滚动...(右键点logo关闭界面可以滚动)
其他网站目前没这个问题...

https://www.baidu.com/s?wd=%E6%84%8F%E7%8A%B9%E5%9C%A8&ie=utf-8

https://user-images.githubusercontent.com/25548230/203754159-325f87dc-ebe4-46dc-be2d-a967fb2e195c.mp4

**Comment by hoothin** [comment]
修复了

**Comment by Noah1995** [comment]
> 修复了

还有几个问题


https://user-images.githubusercontent.com/25548230/204078237-4545710b-841e-487d-8756-9ca97659c9cb.mp4


1丶分组抽屉打开时批量没有提示 容易误触
分组关闭时是有提示的
我是用右键元素想改css突然发现打开好多引擎

全部展开模式也没有提示

2丶you.com引擎似乎无法做到批量
其他引擎都在它没有打开

3丶希望添加新标签页默认后台打开选项开关
场景就是批量打开的时候停在原地继续浏览
我一般等全部刷新完再自行切换引擎标签页

**Comment by hoothin** [comment]
自己点开you，在设置里取消勾选不参与批量打开。
按住ctrl点击分类就是后台打开。

**Comment by Noah1995** [comment]
> 自己点开you，在设置里取消勾选不参与批量打开。 按住ctrl点击分类就是后台打开。

知道了...
感觉设置太多了都不记得有设置这些有的没的...

ctrl+左键分组可以批量后台...
但是拖拽搜索无法新建后台打开...
我想了2种方式
1丶【开启拖拽搜索】
添加【拖拽链接默认后台新标签页打开】

2丶【默认在新标签页打开链接】
添加【启用后链接将全部默认在后台新标签页打开】
添加【排除完整搜索条】
如果添加在这里完整搜索条就不能当前页面引擎跳转只能做排除

**Comment by hoothin** [comment]
好好看説明啊。
拖拽也是一樣的，鬆開滑鼠前按住ctrl就是後臺打開。
反饋前請組織整理好語言。

**Comment by hoothin** [comment]
shift，alt，ctrl+shift，alt+shift 這些打開方式在拖拽、搜索條、快捷鍵調用時都是通用的

**Comment by Noah1995** [comment]
> 好好看説明啊。 拖拽也是一樣的，鬆開滑鼠前按住ctrl就是後臺打開。 反饋前請組織整理好語言。

我不是后台啊
是跳转前台新标签页
我先看看浏览器设置

**Comment by Noah1995** [comment]
> 好好看説明啊。 拖拽也是一樣的，鬆開滑鼠前按住ctrl就是後臺打開。 反饋前請組織整理好語言。

原来要先放开ctrl
我一直按住ctrl是前台新建打开

**Comment by Noah1995** [comment]
我以前都是鼠标党
很少加快捷键操作的
最多复制粘贴
一般都用WGestures手势操作

**Comment by Noah1995** [comment]
> 好好看説明啊。 拖拽也是一樣的，鬆開滑鼠前按住ctrl就是後臺打開。 反饋前請組織整理好語言。

不对不对..
我试了2个浏览器都一样...
拖拽没有不跳转的新建后台标签页
只有新建前台标签页
这个好像分两种情况的...

1丶当关闭【启用后链接将全部默认在新标签页打开】时
ctrl+拖拽是跳转新建标签页
拖拽是跳转当前标签页

https://user-images.githubusercontent.com/25548230/204276327-a9933413-f08a-4d7b-a454-0fb65a64d35b.mp4

2丶当打开【启用后链接将全部默认在新标签页打开】时
ctrl+拖拽是跳转新建标签页
拖拽还是跳转新建标签页

https://user-images.githubusercontent.com/25548230/204279220-e1d98c20-80a9-4a4e-836a-f88bae6c1499.mp4

**Comment by hoothin** [comment]
估計你用的是暴力猴。暴力猴不支持後臺打開新標籤頁，同時暴力猴也不支持繞過安全限制，因此暴力猴也不能在searX等網站上使用。
