### ISSUE TITLE
是否可以不向所有页面添加页面元素

### ISSUE THREAD

**Issue by ted423** [hoothin/SearchJumper#42]
**Describe the bug**
在某页面脚本获取连接，多抓到了两个url
https://www.torrentdownloads.me/search/?search=%s&

随后发现脚本是任何页面都会插入元素。

可以的话，希望在不使用的页面不插入带url的相关元素
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
如果是不使用的页面，正常是不会插入搜索条的。应该是开启页内高亮侧边定位栏导致的吧，因为这个定位侧边栏会监听其他页面添加的全局高亮词。我优化了下，你看下ok没。

**Comment by ted423** [comment]
可以了，非常感谢，辛苦了
