### ISSUE TITLE
【固定不隐藏并且收缩页面】能否做成搜索酱中键点击开和关

### ISSUE THREAD

**Issue by Noah1995** [hoothin/SearchJumper#43]
【固定不隐藏并且收缩页面】能否新增做成搜索酱图标中键点击一键切换开和关
因为我用【WGestures 2】手势操作软件导致长按中键和右键无法呼出搜索酱
只能采用长按左键和划词自动显示
但是很容易误触特别是1688的页面会瞬移

https://user-images.githubusercontent.com/25548230/208086526-df028ddd-616c-4ed4-ac23-70946f03c2dd.mp4

我想要的效果是设置【半隐藏】or【隐藏时使得搜索条完全消失】的情况下
中键搜索酱图标固定和不固定

**Comment by hoothin** [comment]
绑功能键唤出就行了，通过功能键排除误操作。

我写这个就是为了配合右键长按用的。
你的用法好怪，对你而言也许直接去用全局鼠标手势搜索更合适。
