### ISSUE TITLE
怎么才能彻底删除脚本？

### ISSUE THREAD

**Issue by SpaceThing** [hoothin/SearchJumper#45]
怎么才能彻底删除脚本？油猴里面删了之后在greasyfork安装还是会显示"重新安装"，而且再安装上后设置仍然被保留了。

脚本版本1.6.6.54.8

**Comment by hoothin** [comment]
你是否安装了多个脚本管理器？至于设置数据，tm是在打开高级设置的settings里

**Comment by SpaceThing** [comment]
只装了tempermonkey。高级设置的settings是哪里？我从油猴的脚本编辑器直接重置出厂了

**Comment by hoothin** [comment]
那我就不清楚了。你的问题跟这个项目没有关系。你可能需要去脚本管理器相关的地方，例如[tampermonkey](https://github.com/Tampermonkey/tampermonkey)寻求答案。

**Comment by hoothin** [comment]
另外给你提供个信息，有些本地的全局去广告软件自带脚本管理功能，如果你有安装，可以去查看里面是否安装了脚本。

**Comment by 67906980725** [comment]
tampermonkey删除脚本后只是放回收站了, 要再从回收站里删除才会把数据清掉
