### ISSUE TITLE
【功能请求】能否把脚本菜单中的”搜索此项“改为”排除站点“？

### ISSUE THREAD

**Issue by 921j** [hoothin/SearchJumper#46]
脚本很强大！！
但是我发现与其他脚本有冲突，比如在B站搜索页面中，会造成“自动无缝翻页”这个脚本不正常，
希望能添加一个可以快速开关“此站禁用”的选项，虽然自己也能修改脚本或使用脚本管理器的排除功能，但每次更新就会被覆盖或彻底使其在该站隐藏，想用的时候又要改来该去
另外我相信大家如果需要搜索的话，是不会刻意去选择管理器脚本菜单里的“搜索此项”的，为了避免菜单项过长，希望能把这个“搜索此项”改为更加实用的“此站禁用”，请予考虑，谢谢了！

**Comment by hoothin** [comment]
脚本管理器的排除是可以依据域名或者使用正则来匹配的。
自动翻页脚本可以用我的东方永页机。
搜索此项的命令项是为了方便我自己划选时使用右键菜单。
因为是自用，所以开发时纯自嗨，分享倒在其次，没有精力去完善或兼容，见谅。
