### ISSUE TITLE
全部展开模式是否过于灵敏？

### ISSUE THREAD

**Issue by Faith-Mian** [hoothin/SearchJumper#47]
一直在使用作者issue#1的配置，最近选中文字后出现划词小块菜单没有问题，但是鼠标各种操作都很容易触发这个”全部展开模式“，即全屏遮挡的搜索菜单，可是在设置页面搜索相关内容只有”全部展开模式“的快捷键这一个选项且其为空，不知如何精准控制触发，请求帮助T-T

**Comment by hoothin** [comment]
你是如何触发的？有具体重现步骤吗？鼠标操作应该只有拖拽到logo或者点击磁贴的分组icon才会进入全部展开模式

**Comment by Faith-Mian** [comment]
> 

我选中一段文字，右击这段文字或者把鼠标移动到网页最左侧，都会百分百复现全部展开模式，

**Comment by hoothin** [comment]
是什么环境？mac吗？

**Comment by Faith-Mian** [comment]
> 是什么环境？mac吗？有没有安装全局鼠标手势软件？ 另外你说的“全部展开”是指的全屏搜索模式吧？

1. win10x64 
2. 有，但是我对浏览器禁用了
3. 我设置了一个“唤出全部展开模式的快捷键”（区别于“唤出搜索输入框的快捷键”），发现弹出的界面就是我经常看到的那个过于灵敏的页面，所以我这么称呼它
4. 补充一下，我今天没有调整设置，只是更新了一下您的脚本，发现这个问题不存在了：）
