### ISSUE TITLE
有的论坛搜索需要提供 security token 

### ISSUE THREAD

**Issue by mizhewei** [hoothin/SearchJumper#49]
这个 security token  每次登录 或者过期就会失效 有办法持续获取或者绕过吗

**Comment by hoothin** [comment]
贴个地址给我看看

**Comment by mizhewei** [comment]
http://www.anime-sharing.com/

**Comment by hoothin** [comment]
可以这样写`https://www.anime-sharing.com/forum/search.php#p{.textboxcontainer input=%s&click(.searchbutton)}`

**Comment by mizhewei** [comment]
OK了 感谢 另外那个自定义搜索引擎的工具可以设置始终出现吗，比如这里脚本自动识别但其实还要手工调整的情况

**Comment by hoothin** [comment]
我是怕小白误操作所以能自动识别时隐藏了。这种需要手动调整的情况一般也要手动调整选择器，而且抓取工具不能抓xpath，有些元素恐怕必须要用到xpath才能定位，所以暂时不加了，以后如果类似的网站够多再去掉隐藏。

**Comment by mizhewei** [comment]
OK
