### ISSUE TITLE
%u 替换错误，没有转换为当前网页网址

### ISSUE THREAD

**Issue by zhaocai** [hoothin/SearchJumper#50]
**Describe the bug**
**油管视频下载**，配置好`SearchJumper-yt://%u`之后，打开视频，长按右键，之后弹出cmd窗口下载得到的网址类似于`https://www.bilibili.com/4cfdcb41-4e06-4276-be03-013e06cd36bb` 而不是网站的网址 `https://www.bilibili.com/video/BV1dM411T78o/......` 。

问题是%u实际替换的是%t的URL？

**Screenshots**
![image](https://user-images.githubusercontent.com/341473/227910525-b15aac7b-60aa-42ac-95e9-6d098c9aa16c.png)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome + Tampermonkey
 - Version Newest

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/227911717-0cb8365c-d31c-4a69-a68b-697d3b9e62a4.png)
要想获取网页地址，在页面右键就行了

**Comment by zhaocai** [comment]
> ![image](https://user-images.githubusercontent.com/5361213/227911717-0cb8365c-d31c-4a69-a68b-697d3b9e62a4.png) 要想获取网页地址，在页面右键就行了

上面说的”when pointing to a link or picture, it means the corresponding url“，这不是和%t重复了吗？如何同时需要网站URL和对应指向的URL怎么办呢？

整个视频组设置成 `Effect on  Video`, 只有点击在视频时才响应；这还是从你的配置抄来的。

**Comment by hoothin** [comment]
如果存在%t, %u就还是页面地址
