### ISSUE TITLE
【隐藏时使得搜索条完全消失】添加一下鼠标再次点击空白处才隐藏

### ISSUE THREAD

**Issue by Noah1995** [hoothin/SearchJumper#53]
![image](https://user-images.githubusercontent.com/25548230/230261561-2fc50aca-4724-4477-97f3-ddc7fc8abd3e.png)
开启【隐藏时使得搜索条完全消失】添加一下鼠标再次点击空白处才隐藏
不然鼠标触摸后不小心移出工搜索栏经常自动消失

**Comment by Noah1995** [comment]
![录制_2023_04_06_11_11_36_497](https://user-images.githubusercontent.com/25548230/230263056-259f1775-5a65-41b6-8ca0-61933eddf47e.gif)

**Comment by hoothin** [comment]
这个建议不错。现在忙工作，晚些时候加个选项

**Comment by hoothin** [comment]
已經加上了
