### ISSUE TITLE
历史站点的图标不显示

### ISSUE THREAD

**Issue by zhaocai** [hoothin/SearchJumper#55]
**Describe the bug**
如下图，历史站点的图标不显示。这些站点图标正常是可以显示并已经缓存过的（例如第二张图）。

![show-all-mode](https://s2.loli.net/2023/04/09/UvhQx9p6FcMDfIm.png)
![history-site](https://files.catbox.moe/iyuf83.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome+Tempermonkey
 - Version: Latest

**Comment by hoothin** [comment]
感謝報錯，修復了

**Comment by zhaocai** [comment]
多谢！

**Comment by zhaocai** [comment]
顺便问一下,图标都是缓存的,但是在下面这个网站所有图标都不能显示是什么原因呢? [windhawk](https://windhawk.net/)

![](https://s2.loli.net/2023/04/09/c5R8Di1XIrlBVYE.png)

**Comment by hoothin** [comment]
因爲csp
```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline' 'self'; img-src 'self' https://i.imgur.com https://raw.githubusercontent.com https://www.google-analytics.com; script-src 'self' 'sha256-dJVVWLaj91eVeD57uZcfzgpO93mwHITk0K9QTssMY4A=' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com; connect-src 'self' https://mods.windhawk.net https://www.google-analytics.com; font-src 'self';">
```
這個站只允許本站或者以上三個源的圖片，不允許base64地址

**Comment by hoothin** [comment]
想要顯示圖片，用擴展禁止 csp 就可以了。不過沒必要，也不建議
