### ISSUE TITLE
YouTube 等视频网站，进入视频后迅速全屏会因为搜索酱拦截而回退到窗口

### ISSUE THREAD

**Issue by zhaocai** [hoothin/SearchJumper#57]
**Describe the bug**
YouTube 等视频网站，进入视频后迅速全屏会因为搜索酱拦截而回退到窗口。如下图所示：
![fullscreen_blocker](https://user-images.githubusercontent.com/341473/232023452-d9f9525f-6fa3-4759-bc3d-3d8f4eed61bd.gif)

如果在 Tampermonkey 中关掉搜索酱就不会有这个问题。不算什么大的 Bug，只是我经常点击视频很快选择全屏每次都回退不是很方便，现在我都是等几秒再点全屏。

**To Reproduce**
1. 进入视频网站，点开视频
2. 在 １ 秒内点击或快捷键全屏
3. 全屏会因为搜索酱拦截而回退到窗口

**Desktop (please complete the following information):**
 - OS: WindowsOS
 - Browser Chrome + Tampermonkey
 - Version Latest

**Comment by hoothin** [comment]
奇怪了，我没写过相关的功能。只有一个在全屏时隐藏搜索酱的方法，但是应该也不会导致拦截。
我尝试在 youtube 上测试也没有重现。是否有可能是你本地和某些扩展冲突了呢？

**Comment by hoothin** [comment]
你现在是关掉搜索酱就不会出现这种情况了吗？

**Comment by zhaocai** [comment]
我把搜索酱顺序改到最前之后就好了，可能是下面几个脚本的问题吧，多谢了！
![quicker_ea6550cd-929c-4ef8-ab20-c494350dc295](https://user-images.githubusercontent.com/341473/232034083-a8db5701-cf04-460c-a483-7197d30fa9c1.png)

**Comment by hoothin** [comment]
你可以试下我的[永页机](https://greasyfork.org/en/scripts/438684-pagetual)不？

**Comment by zhaocai** [comment]
> 你可以试下我的[永页机](https://greasyfork.org/en/scripts/438684-pagetual)不？

试过的，也是非常牛的脚本！我很早之前用一个叫做 autopager 的 chrome 插件，后来发现一个应该是叫做 superloader_plus 的脚本，用了挺久；之后 superloader_plus 这个脚本很久没更新不太能用了才去找，发现[永页机](https://greasyfork.org/en/scripts/438684-pagetual) 立马就切换过去，当时感觉做到这样已经完美了。直到碰到`自动无缝翻页`，功能差不多甚至有不少网站不支持，但去掉了中间翻页的 banner 体验感觉更好。如下图，翻页完全无缝连接，只是在左下有个隐蔽的页数提示。

![quicker_3e8d22a8-14b3-4f7a-b5e9-4bb0a997cc32](https://user-images.githubusercontent.com/341473/232050183-efa2eec6-6954-49be-98e0-17653e5a5192.png)

**Comment by zhaocai** [comment]
原来还有这个功能👍，之前没注意，试了一下真不错！现在觉得差点意思的就是这个图标，既然目的是无缝体验：

- 透明度还可以再低一点
- 数字放到边上不是很美观，直接不要太极图标换成数字应该更好。
- 
![image](https://user-images.githubusercontent.com/341473/232264008-f54fc470-e81e-4f7f-a2ef-7f05bbf47258.png)

**Comment by zhaocai** [comment]
另外设置可以单独添加一个 `Toggle Immersive Experience`，不然都不知道有这样的功能。

**Comment by hoothin** [comment]
设置里是有这个选项的，在【使拼接页面的内容在新页面打开】下面

**Comment by zhaocai** [comment]
> 你如果不喜欢太极图标，设置里也可以换掉。支持图片地址，base64图片，也支持直接用文字，例如"🌐"
不是不喜欢太极图标，而是不喜欢把页数放在图标的右上角；这里最关键的信息是页数，把最关键的信息缩小右上标显示，第一眼注意到的”主角“成了图标，不知道符合不符合界面设计的原则；使用过程中也不会盯着看，但每次余光扫过时总有一种突兀不和谐的感觉。

**Comment by hoothin** [comment]
你更新试试，如果是这个需求，最新版已经是这样了

**Comment by zhaocai** [comment]
> 你更新试试，如果是这个需求，最新版已经是这样了

效率真高！目前已经相当满意！

前面说的选项是单独给`无缝翻页`添加一个选项，现在是需要自己去找几个选项。对不知道有这个功能的用户可能根本不会去找。

**Comment by hoothin** [comment]
侧边栏还有几个隐藏功能你可以试试，单击是切换禁用，右击是打开菜单，拖动可以记录位置，点击前往页尾时会暂时禁用，按住alt点击前往页尾时不会禁用。
