### ISSUE TITLE
请求添加一个选中文字自动复制的功能

### ISSUE THREAD

**Issue by liangxyz** [hoothin/SearchJumper#58]
如题，感谢大佬分享的脚本，非常好用，就是经常需要复制粘贴，能否增加一个选中网页文字就自动复制的功能？万分感谢

**Comment by hoothin** [comment]
那不应该用搜索酱来实现吧。试试这个 [Auto Copy](https://microsoftedge.microsoft.com/addons/detail/auto-copy/dccbmdgkdanddjmfehgigdhcijadgfkc) 或者这个 [自动剪切板](https://microsoftedge.microsoft.com/addons/detail/%E8%87%AA%E5%8A%A8%E5%89%AA%E5%88%87%E6%9D%BF/oecjpmpbghigjifackhbapkamgaemnkj)
