### ISSUE TITLE
请优化一下，使得当鼠标滑过的时候，请不要再次展开，除非主动点击。

### ISSUE THREAD

**Issue by FeiLZX3Km** [hoothin/SearchJumper#59]
在搜索页面时，部分分组是展开的，是下图的样子。
<img width="379" alt="微信截图_20230504122700" src="https://user-images.githubusercontent.com/21981195/236112646-dd3214a3-961a-4736-8d39-1c8d3a8a5e6b.png">
但当鼠标滑过的时候，会再次展开，容易点错。如下图
<img width="726" alt="微信截图_20230504122715" src="https://user-images.githubusercontent.com/21981195/236112796-9d9b6c2c-fa9c-46c8-90dc-4e8a823e8a54.png">
请优化一下，使得当鼠标滑过的时候，请不要再次展开，除非主动点击。

**Comment by hoothin** [comment]
难道不是你自己开启的极简模式吗？

**Comment by FeiLZX3Km** [comment]
> 难道不是你自己开启的极简模式吗？

是的。极简模式是我开的。
请问可否在极简模式下，别让它再次展开？

**Comment by hoothin** [comment]
什么意思？描述清楚一点呢。如果鼠标划过不展示所有分类，那你想要点哪触发？

**Comment by hoothin** [comment]
我自己是把搜索条放在浏览器左上角的。容易点错的话，除非是放在中间区域。你可以试试换个位置

**Comment by FeiLZX3Km** [comment]
> 什么意思？描述清楚一点呢。如果鼠标划过不展示所有分类，那你想要点哪触发？
 
鼠标滑过已经展开的分组，如搜索引擎分组的时候——
1. 其他分组默认仍收藏在猫咪头图标里。不点击猫咪头就不展开，这样更加“极简”。
2. 固定已经展开分组的位置。使用户在点击或者滑过猫咪头展开分组时，已经固定位置的分组，不会因为其他分组的展开而产生位移。这样可以使得用户鼠标指哪儿就点哪儿，一步到位，无须顾虑是否会点错。

**Comment by hoothin** [comment]
猫咪头不是用来展开分组，而是用来进入showall模式的。因此不可行。
分组位置正如我在上文所述，是根据搜索条位置确定的。如果在四角，就是根据相应锚点射线展开，那样已展开分组自然是固定的。否则若是如你现在这样放在中间，那展开时便会居中

**Comment by hoothin** [comment]
更新了一版。我考虑了一下，虽然通过萌脸取消最小化不可行，但是通过关闭当前分组来触发取消是没问题的。你试试。

**Comment by FeiLZX3Km** [comment]
> 更新了一版。我考虑了一下，虽然通过萌脸取消最小化不可行，但是通过关闭当前分组来触发取消是没问题的。你试试。

好的，谢谢指点了~
