### ISSUE TITLE
Seek help for rule of chrome://xxx

### ISSUE THREAD

**Issue by OrangeCatSleepless** [hoothin/SearchJumper#60]
大佬可以跳转到指定页面吗? 类似于 chrome://extensions/ 或 chrome://extensions/ 之类的 Chrome 设置页面

直接这样写好像跳不过去?

![chrome_wN94Zr8kPz](https://user-images.githubusercontent.com/58691431/236616593-bbe1271a-ba89-4f92-9f77-a7523f0d6a05.png)

**Comment by hoothin** [comment]
已经添加支持了，更新一下试试

**Comment by OrangeCatSleepless** [comment]
> 已经添加支持了，更新一下试试

非常完美👍
