### ISSUE TITLE
无法快速添加搜索引擎

### ISSUE THREAD

**Issue by OrangeCatSleepless** [hoothin/SearchJumper#61]
**Describe the bug**

大佬，这个页面
 
https://ping.sx/ping 

无法使用快捷键添加搜索引擎 右键里的也不行

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
多谢报错，修复了

**Comment by OrangeCatSleepless** [comment]
> 多谢报错，修复了

还有一个小问题 现在快捷键是正常调出来了 但是模拟点击之后 不管按哪里都成了删除

![chrome_MruChTKBmb](https://user-images.githubusercontent.com/58691431/236800444-413d1aa8-561c-4559-a4c8-187b09337fee.png)

![chrome_V88VDRxg2q](https://user-images.githubusercontent.com/58691431/236800590-951bc0c2-3ca7-4236-93af-487df5e8197d.png)


预期结果

![chrome_jjzNaY0mYj](https://user-images.githubusercontent.com/58691431/236800819-1919bf99-037b-41ad-951e-0af12b576d94.png)

**Comment by OrangeCatSleepless** [comment]
人傻了,是我默认开了翻译导致的🤣很完美,没问题了

**Comment by hoothin** [comment]
这个站可以先搜索进入搜索结果页，再通过快捷键添加
最佳规则是 `https://ping.sx/ping?protocol=auto&t=%u`，用不着模拟

**Comment by OrangeCatSleepless** [comment]
> 这个站可以先搜索进入搜索结果页，再通过快捷键添加 最佳规则是 `https://ping.sx/ping?protocol=auto&t=%u`，用不着模拟

主要是想通过模拟自动点一下 ping

**Comment by OrangeCatSleepless** [comment]
大佬,帮忙看一下这个 

```
https://ping.sx/ping#p{sleep(1000)&#target=%h&click(#__next > div.flex > main.flex-grow > section.relative > div > form > div.flex > div > div.flex > button > span)}
```

在 https://ping.sx/ping 可以获取并且点击 其他的页面就不行了😂 脑子不够用了

**Comment by hoothin** [comment]
什么意思？这个规则就是在 https://ping.sx/ping 生效的呀，我测试了一下也是可以用的。你说的“其他页面”是什么页面？

**Comment by OrangeCatSleepless** [comment]
> 什么意思？这个规则就是在 https://ping.sx/ping 生效的呀，我测试了一下也是可以用的。你说的“其他页面”是什么页面？

就是比如我随便打开一个网页 通过快捷键调出来 之后自动获取当前页面域名 然后跳转 https://ping.sx/ping 输入框输入获取的域名 点击 ping

预期效果跟这个 itdog 规则达成的一样，不管在哪个页面快捷键调出之后都可以获取域名并且跳转 https://www.itdog.cn/ping 在输入框输入获取的域名并且点击 ping

```
https://www.itdog.cn/ping/#p{#ip=%h&click(#screenshots > div.pcoded-inner-content > div.main-body > div.page-wrapper > div.col-12 > div.card > div.row > div.col > div.row > button.btn > i.feather.icon-play)}
```

现在这个 ping.sx 的规则 在 ping.sx 页面可以做到自动获取域名之后输入并点击 ping 但换一个就不行了

```
https://ping.sx/ping#p{sleep(1000)&#target=%h&click(#__next > div.flex > main.flex-grow > section.relative > div > form > div.flex > div > div.flex > button > span)}
```

**Comment by hoothin** [comment]
我还是不理解你的问题。你是说这个规则只在ping.sx生效吗？可是我在baidu.com测试了也是没问题的呀

**Comment by OrangeCatSleepless** [comment]
> 我还是不理解你的问题。你是说这个规则只在[ping.sx](http://ping.sx)生效吗？可是我在[baidu.com](http://baidu.com)测试了也是没问题的呀

对啊，我反复测试只在 ping.sx 生效，baidu.com 我刚刚去测试了 没效果 使用之后 跳转的页面是 https://ping.sx/ping 没有获取到 `baidu.com` 这个域名 没有任何操作 我还用 Chrome 和 Edge 都试了一下这个规则都只在 ping.sx 生效

**Comment by OrangeCatSleepless** [comment]
![msedge_H3iUSPNS7S](https://github.com/hoothin/SearchJumper/assets/58691431/bfd9990c-c374-44f5-8f35-8d49321388bb)

**Comment by OrangeCatSleepless** [comment]
> 你打开控制台看一下是卡在哪一步了。模拟操作的每一步都会有输出

这要怎么看 我在 ping.sx 页面是能看到 
![chrome_8ltsGu4fMe](https://github.com/hoothin/SearchJumper/assets/58691431/240a24d4-5022-49ff-a2bc-089d12adc5ac)
 换一个页面点完就跳到 ping.sx 控制台看不到啊

**Comment by hoothin** [comment]
你看下，跳转到 ping.sx 之后，脚本管理器还在运行吗？

**Comment by hoothin** [comment]
我的意思是，你浏览器上的脚本管理器（tm或者暴力猴之类）在跳转到 ping.sx 之后是否还在运行？
我看你有安装“沉浸式翻译”，那个扩展代码错误比较多，也许是这个或者其他某个扩展冲突导致脚本管理器在跳转后没有继续运行。
因为我没有办法复现你的 bug，所以还得在你本地找原因了。

**Comment by OrangeCatSleepless** [comment]
> 我的意思是，你浏览器上的脚本管理器（tm或者暴力猴之类）在跳转到 [ping.sx](http://ping.sx) 之后是否还在运行？ 我看你有安装“沉浸式翻译”，那个扩展代码错误比较多，也许是这个或者其他某个扩展冲突导致脚本管理器在跳转后没有继续运行。 因为我没有办法复现你的 bug，所以还得在你本地找原因了。

在运行的，我能在控制台看到其他脚本执行。刚刚关闭了除 tm 之外所有插件 并且只开启了了 SearchJumper 一个脚本的情况下测试这个规则仍旧不行。控制台是这样的 

ping.sx 页面

![msedge_NXMljCXYwd](https://github.com/hoothin/SearchJumper/assets/58691431/8e0369ed-8029-4a0f-83b2-cef6777c209e)

baidu.com 页面

![msedge_ZRRtasA3Fd](https://github.com/hoothin/SearchJumper/assets/58691431/fdf863f2-229a-4c32-82a4-1378a7b3aa85)

**Comment by hoothin** [comment]
你检查下本地是否有多个在 ping.sx 生效的规则？

**Comment by OrangeCatSleepless** [comment]
> 你检查下本地是否有多个在 [ping.sx](http://ping.sx) 生效的规则？

笑死🤣人傻了，真的是这个原因，我打算改好了生效再把另一个删掉来着，没想到一直不生效就是因为还有一个😂

解决了，麻烦大佬了，谢谢！
