### ISSUE TITLE
在Bing搜索页面的小缺陷

### ISSUE THREAD

**Issue by arpir** [hoothin/SearchJumper#72]
在设置->页内查找，开启高亮搜索引擎页面的两个设置，之后在Bing搜索引擎中，输入框中的搜索词也一同被高亮，这个时候如果我想再次编辑搜索词，那个高亮的关键字始终高亮着，实际上我这个时候文字已经发生了修改，造成看起来输入框中的搜索词无法被修改一样。而这样的问题在百度和Google搜索引擎中并不会出现。

**Comment by arpir** [comment]
在百度和Google搜索引擎中输入框中的搜索词是正常显示的，不会被高亮，这样的效果应该才是正常的。我使用的是Edge浏览器，这个问题存在很久了，不知道是Bing搜索引擎的原因还是脚本的问题。

**Comment by hoothin** [comment]
因为那不是输入框，是覆盖在 textarea 上的普通文字。所以建议关闭在搜索引擎页面高亮，只开启在跳转页高亮，否则会有很多不可预料的问题。例如卡死页面，影响单页应用的元素引用导致无法移除之类的。
我有空会再优化一下这个。
