### ISSUE TITLE
New Bing 输入框与快捷键冲突

### ISSUE THREAD

**Issue by OrangeCatSleepless** [hoothin/SearchJumper#74]
**Describe the bug**

在 NewBing 页面的对话框中输入  ` 时 

会直接调用快捷键导致无法正常输入  ` 字符

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
在设置里关闭`监听输入框`，或者为快捷键添加功能键，例如`` Alt+` ``

**Comment by OrangeCatSleepless** [comment]
> 在设置里关闭`监听输入框`，或者为快捷键添加功能键，例如`` Alt+` ``

不不不，我并没有启用监听输入框 并且这个现象只在 NewBing 页面出现 其他搜索引擎或其他页面的输入框是正常的

更具体点来说是在 https://www.bing.com/search?q=Bing+AI&showconv=1 这个页面聊天页面

搜索时是正常的

![chrome_6jxbMoRO6m](https://github.com/hoothin/SearchJumper/assets/58691431/91baf24f-cbc6-4f8e-8190-4b6966f96faf)

**Comment by OrangeCatSleepless** [comment]
> 因为new bing 对话框是藏在shadow dom里的。 我默认设置里没加 alt，但我自用配置加了alt。还是建议你加个功能键来用。

原来是这样，感谢大佬
