### ISSUE TITLE
当分组图标为空时，无法拖拽排序（我使用了类似划词翻译的插件）

### ISSUE THREAD

**Issue by Gloryandel** [hoothin/SearchJumper#76]
1. 当分组只有组名  
![image](https://github.com/hoothin/SearchJumper/assets/51497852/220b9c19-8861-4720-9f82-a85526529994)  
2.  拖拽排序时会选中文字而无法拖动排序
![image](https://github.com/hoothin/SearchJumper/assets/51497852/eb8acb8c-d4ea-4865-887a-7d0b115b2a99)

**Smartphone (please complete the following information):**
 - Device: Windows
 - OS: Windows 11
 - Browser Vivaldi

**Additional context**
脚本内置的图标是透明背景的，图标上的文案是argb值是多少？想统一图标风格，毕竟搜索酱内置图标挺好看的。图标文案纯白0xffffff，背景透明很相似，但是在搜索时有一点不一样😂

**Comment by hoothin** [comment]
我试了下没重现你的问题，你安装了限制去除之类的脚本没有？

**Comment by Gloryandel** [comment]
颜色我知道了（214, 225, 234）

**Comment by Gloryandel** [comment]
> 我试了下没重现你的问题，你安装了限制去除之类的脚本没有？ 分类图标我给了user-select none，所以是不可能被选中的。 搜索酱没有内置图标，你看到的是字体，因此没有颜色，css 里面给什么颜色就会显示什么颜色。

试了，应该是沙拉查词扩展的问题，导致所有不止分类，包括分类下的站点都有问题。但是沙拉查词没有黑名单😂

**Comment by Gloryandel** [comment]
> > 我试了下没重现你的问题，你安装了限制去除之类的脚本没有？ 分类图标我给了user-select none，所以是不可能被选中的。 搜索酱没有内置图标，你看到的是字体，因此没有颜色，css 里面给什么颜色就会显示什么颜色。
> 
> 试了，应该是沙拉查词扩展的问题，导致所有不止分类，包括分类下的站点都有问题。但是沙拉查词没有黑名单😂

不对不对，等一下😂绝对是[Select like opera](https://git.oschina.net/coldfire/GM/raw/master/select.user.js)脚本的问题。它是解决Chrome 不能选择链接文本问题的。大佬看可能对这类脚本做兼容吗？不是很严重。不能就 Close了。我做下排除就行了，还以为是搜索酱的问题

**Comment by Gloryandel** [comment]
> 我试了下没重现你的问题，你安装了限制去除之类的脚本没有？ 分类图标我给了user-select none，所以是不可能被选中的。 搜索酱没有内置图标，你看到的是字体，因此没有颜色，css 里面给什么颜色就会显示什么颜色。

![image](https://github.com/hoothin/SearchJumper/assets/51497852/11342391-cffb-4b27-8bfd-d37b71d59814)
文字上面那个图标也是字体吗？

**Comment by hoothin** [comment]
chrome 可以按住 alt 選取鏈接上的文字。select like boss 有對應的擴展，兼容性比脚本要好。
圖標都是字體，例如 https://fontawesome.com/v6/search?q=book&m=free。其他的圖標你可以自己搜索，然後填入。例如百科的圖標填入 book 就行

**Comment by Gloryandel** [comment]
👌👍👍👍
