### ISSUE TITLE
能否改进下显示隐藏工具条的机制

### ISSUE THREAD

**Issue by Xnjikol** [hoothin/SearchJumper#8]
以前用过一个类似的脚本，逻辑是勾选了文本后工具条立即出现，取消勾选后工具条消失。
有时候我只是需要查询这个页面上的一个词，但是打开后这个工具条会一直显示，不会自动隐藏（指完全看不见）。
也希望增加一个开关，可以将工具条设置为划词后立即出现，感觉会比较方便

**Comment by hoothin** [comment]
不是已经有了吗？”划选立即显示“这个选项，隐藏的话右击笑脸就行。

**Comment by hoothin** [comment]
容我吐槽一下，为啥你们都把它当作右键搜来用呀。我明明是写来做搜索引擎快捷切换的。右键搜可以直接用更加强大的 ContextSearch-web-ext 呀

**Comment by Xnjikol** [comment]
其实我一开始想找的就是右键搜索的脚本😂，因为chrome右键搜索只能固定一个搜索引擎，感觉不方便。但是我原先用的那个它不更新了，然后就找到你这个了,确实没有注意到区别。

另外，我好像找到一个bug：同时勾选“自动合上类别”与“划选立即调用”，并且划词后，会无法切换类别。
![动画](https://user-images.githubusercontent.com/61531165/171546412-4e709fef-0dab-4e5d-98f0-e5bcad886a55.gif)

**Comment by hoothin** [comment]
感谢反馈bug，我修一下。

不过右键搜索的话强烈推荐 ContextSearch-web-ext 这个，我现在也在用，可以配合网上其他人分享的配置文件，使用体验很不错。

**Comment by hoothin** [comment]
另外你没有导入我的站点配置吗？https://github.com/hoothin/SearchJumper/issues/1 这里的站点要比默认的多得多了

**Comment by hoothin** [comment]
上面提到的问题已经修复了，另外添加了右击类别批量打开该类别下所有网站的功能。

**Comment by Xnjikol** [comment]
大佬回复真的快，给star了。🐄🍺
