### ISSUE TITLE
脚本配置问题

### ISSUE THREAD

**Issue by upsetdone** [hoothin/SearchJumper#9]
在配置页面完成配置后无法应用(显示成功但未被应用，代码页面可见)。
尝试修改脚本代码，但在线配置页面导出结构与脚本配置部分结构不一致，失败。

**Comment by hoothin** [comment]
是导出页面吗？你修改的配置能发上来吗？显示提示是什么？你的本地环境是什么？有更多报错信息吗？

**Comment by upsetdone** [comment]
> 
[searchJumper.txt](https://github.com/hoothin/SearchJumper/files/8836896/searchJumper.txt)
![image](https://user-images.githubusercontent.com/71574060/171977694-0a5a9dba-70c1-412a-8f4a-ae86803cf2c0.png)
Edge目前最新版
无报错
只使用暴力猴

**Comment by upsetdone** [comment]
> 是导出页面吗？你修改的配置能发上来吗？显示提示是什么？你的本地环境是什么？有更多报错信息吗？
> 
> 另外你检查下本地有没有装多个脚本管理器？

![image](https://user-images.githubusercontent.com/71574060/171977736-fcf9c425-04d5-4ae9-80e4-d2b6f458254e.png)

**Comment by hoothin** [comment]
感谢反馈，暴力猴确实有问题，因为unsafewindow没有权限，我试试重构一下，改成cs模式。

**Comment by upsetdone** [comment]
> 感谢反馈，暴力猴确实有问题，因为unsafewindow没有权限，我试试重构一下，改成cs模式。

好的

**Comment by hoothin** [comment]
改好了，你试试。

我的测试环境是edge 102.0.1245.30 + 暴力猴 v2.13.0

**Comment by upsetdone** [comment]
> 用，代码页

OK了，非常感谢




我冒昧再提几个建议：

1.自动展开速度调节：
比手动点慢，等展开的那一下体验有些断层

2.增加展开样式：
同一级展开不太好点击
不知道是不是bug，更喜欢这样的
![image](https://user-images.githubusercontent.com/71574060/171983956-9f330653-2dd7-46fb-80da-b93855d3b48a.png)

3.划词即搜：
贴边有点远（图为划词翻译扩展）
![image](https://user-images.githubusercontent.com/71574060/171983753-e63a1010-20bd-4e73-9add-3488fbc93be7.png)
3.5：调整整体大小

4.搜图长按时间控制：
太久了1s

**Comment by hoothin** [comment]
多谢建议，我给展开速度、整体大小和长按时间加几个设置项吧。
下拉样式可以尝试 search engine jump 这个油猴脚本。我的使用场景是开启“默认不贴边隐藏”选项，访问某个搜索引擎后同类别的其他图标平摊展开，方便我快速跳转，而下拉菜单还得挨个用鼠标去展开，所以我并不想要下拉样式。
划词后悬浮图标跟随鼠标这个可以尝试 【右键搜】 这个扩展。我目前的使用场景是为单个站设置快捷键之后划词直接通过快捷键搜索或者在想要搜索时去页面底部搜索，所以我对这个也没需求。

**Comment by upsetdone** [comment]
了解

关于下拉样式，我倾向于向下自动展开。

哈哈，陷入误区了，一个扩展实在难以做到尽善尽美，而在用的已经能满足绝大部分要求了

感谢

**Comment by hoothin** [comment]
你尝试过拖拽至右侧贴边了吗？那样就是向下展开啦

**Comment by upsetdone** [comment]
> 你尝试过拖拽至右侧贴边了吗？那样就是向下展开啦

但是还是在同一父级下啊
![176F6D84](https://user-images.githubusercontent.com/71574060/171986356-d66ffefc-4352-4854-9dca-ed0ea11c75e6.png)
向下指的是类似search engine jump的子级展开

**Comment by hoothin** [comment]
你上面示意图描述的和[”一键离线下载“](https://greasyfork.org/scripts/22590-easy-offline)很像，改天我也把跳转功能加到一键离线下载里去吧。那样下拉和悬浮跟随就都有了

**Comment by upsetdone** [comment]
> 

https://i0.hdslb.com/bfs/emote/89516218158dbea18ab78e8873060bf95d33bbbe.png@100w_100h.webp

**Comment by upsetdone** [comment]
![17D4A39C](https://user-images.githubusercontent.com/71574060/171989716-1b2bf3f7-eb7c-42eb-80a1-7c2703be6a68.png)

**Comment by hoothin** [comment]
关于下拉列表，最新版已经加上了，只需要在设置里开启即可。
