### ISSUE TITLE
自定义Post请求的body

### ISSUE THREAD

**Issue by 821869798** [hoothin/SearchJumper#91]
想咨询下作者，能不能自定义post请求的body，我想划词调用翻译软件，需要把选中内容直接当作整个body，我使用`http://127.0.0.1:60828/translate%P{%sr}`来作为请求，请求体会自动变成`{ "%sr" : "" }` 。例如我选中了名为`name`的单词，发送的body会变成`{ "name" : "" }`。如何只想发%sr的内容，应该如何做呢。

**Comment by hoothin** [comment]
1.6.30.5 增加了对 raw 数据的支持，用法是通过双引号包裹，例如`http://127.0.0.1:60828/translate%P{"%sr"}`

**Comment by 821869798** [comment]
确实可以。👍
