### ISSUE TITLE
hoothin.github.io is constantly reloading

### ISSUE THREAD

**Issue by iG8R** [hoothin/SearchJumper#99]
**Describe the bug**
Hi.
Your site page [hoothin.github.io/SearchJumper](https://hoothin.github.io/SearchJumper) is constantly reloading without any external intervention.

**To Reproduce**
1. Go to [hoothin.github.io/SearchJumper](https://hoothin.github.io/SearchJumper)
2. See error how the page is constantly reloading.

**Expected behavior**
When a user visits a website page, it should not disturb them by constantly reloading.

**Screenshots**

[SearchJumper-Constant-Reload-Video_2023-10-30_231952.webm](https://github.com/hoothin/SearchJumper/assets/11407417/3c766a62-21a1-43e0-a581-221075bd7db2)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0 64bit
 - Browser: Chrome 118.0.5993.90 (Official Build) (64-bit)
 - Browser: Edge 118.0.2088.69 (Official build) (64-bit)

**Comment by hoothin** [comment]
Install SearchJumper at first.
